package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BalanceTransfers generated by hbm2java
 */
@Entity
@Table(name = "balance_transfers", schema = "1")
public class BalanceTransfers implements java.io.Serializable {

	private BalanceTransfersId id;

	public BalanceTransfers() {
	}

	public BalanceTransfers(BalanceTransfersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "transferId", column = @Column(name = "transfer_id") ),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 29) ),
			@AttributeOverride(name = "transferLimitDate", column = @Column(name = "transfer_limit_date", length = 29) ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ) })
	public BalanceTransfersId getId() {
		return this.id;
	}

	public void setId(BalanceTransfersId id) {
		this.id = id;
	}

}
