package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BalanceTransactionsId generated by hbm2java
 */
@Embeddable
public class BalanceTransactionsId implements java.io.Serializable {

	private Integer userId;
	private BigDecimal credit;
	private BigDecimal debit;
	private BigDecimal totalAmount;
	private Date createdAt;
	private Serializable source;

	public BalanceTransactionsId() {
	}

	public BalanceTransactionsId(Integer userId, BigDecimal credit, BigDecimal debit, BigDecimal totalAmount,
			Date createdAt, Serializable source) {
		this.userId = userId;
		this.credit = credit;
		this.debit = debit;
		this.totalAmount = totalAmount;
		this.createdAt = createdAt;
		this.source = source;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "credit", precision = 131089, scale = 0)
	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

	@Column(name = "debit", precision = 131089, scale = 0)
	public BigDecimal getDebit() {
		return this.debit;
	}

	public void setDebit(BigDecimal debit) {
		this.debit = debit;
	}

	@Column(name = "total_amount", precision = 131089, scale = 0)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "source")
	public Serializable getSource() {
		return this.source;
	}

	public void setSource(Serializable source) {
		this.source = source;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BalanceTransactionsId))
			return false;
		BalanceTransactionsId castOther = (BalanceTransactionsId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getCredit() == castOther.getCredit()) || (this.getCredit() != null
						&& castOther.getCredit() != null && this.getCredit().equals(castOther.getCredit())))
				&& ((this.getDebit() == castOther.getDebit()) || (this.getDebit() != null
						&& castOther.getDebit() != null && this.getDebit().equals(castOther.getDebit())))
				&& ((this.getTotalAmount() == castOther.getTotalAmount())
						|| (this.getTotalAmount() != null && castOther.getTotalAmount() != null
								&& this.getTotalAmount().equals(castOther.getTotalAmount())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getSource() == castOther.getSource()) || (this.getSource() != null
						&& castOther.getSource() != null && this.getSource().equals(castOther.getSource())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getCredit() == null ? 0 : this.getCredit().hashCode());
		result = 37 * result + (getDebit() == null ? 0 : this.getDebit().hashCode());
		result = 37 * result + (getTotalAmount() == null ? 0 : this.getTotalAmount().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getSource() == null ? 0 : this.getSource().hashCode());
		return result;
	}

}
