package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContributionDetailsId generated by hbm2java
 */
@Embeddable
public class ContributionDetailsId implements java.io.Serializable {

	private Integer id;
	private Integer contributionId;
	private Integer paymentId;
	private Integer userId;
	private Integer projectId;
	private Integer rewardId;
	private String permalink;
	private String projectName;
	private String projectImg;
	private Date projectOnlineDate;
	private Date projectExpiresAt;
	private String projectState;
	private String userName;
	private String userProfileImg;
	private String email;
	private Boolean anonymous;
	private String payerEmail;
	private String key;
	private BigDecimal value;
	private Integer installments;
	private BigDecimal installmentValue;
	private String state;
	private Boolean isSecondSlip;
	private String gateway;
	private String gatewayId;
	private BigDecimal gatewayFee;
	private Serializable gatewayData;
	private String paymentMethod;
	private Date createdAt;
	private Date pendingAt;
	private Date paidAt;
	private Date refusedAt;
	private Date pendingRefundAt;
	private Date refundedAt;
	private Date deletedAt;
	private Date chargebackAt;
	private Serializable fullTextIndex;
	private Boolean waitingPayment;

	public ContributionDetailsId() {
	}

	public ContributionDetailsId(Integer id, Integer contributionId, Integer paymentId, Integer userId,
			Integer projectId, Integer rewardId, String permalink, String projectName, String projectImg,
			Date projectOnlineDate, Date projectExpiresAt, String projectState, String userName, String userProfileImg,
			String email, Boolean anonymous, String payerEmail, String key, BigDecimal value, Integer installments,
			BigDecimal installmentValue, String state, Boolean isSecondSlip, String gateway, String gatewayId,
			BigDecimal gatewayFee, Serializable gatewayData, String paymentMethod, Date createdAt, Date pendingAt,
			Date paidAt, Date refusedAt, Date pendingRefundAt, Date refundedAt, Date deletedAt, Date chargebackAt,
			Serializable fullTextIndex, Boolean waitingPayment) {
		this.id = id;
		this.contributionId = contributionId;
		this.paymentId = paymentId;
		this.userId = userId;
		this.projectId = projectId;
		this.rewardId = rewardId;
		this.permalink = permalink;
		this.projectName = projectName;
		this.projectImg = projectImg;
		this.projectOnlineDate = projectOnlineDate;
		this.projectExpiresAt = projectExpiresAt;
		this.projectState = projectState;
		this.userName = userName;
		this.userProfileImg = userProfileImg;
		this.email = email;
		this.anonymous = anonymous;
		this.payerEmail = payerEmail;
		this.key = key;
		this.value = value;
		this.installments = installments;
		this.installmentValue = installmentValue;
		this.state = state;
		this.isSecondSlip = isSecondSlip;
		this.gateway = gateway;
		this.gatewayId = gatewayId;
		this.gatewayFee = gatewayFee;
		this.gatewayData = gatewayData;
		this.paymentMethod = paymentMethod;
		this.createdAt = createdAt;
		this.pendingAt = pendingAt;
		this.paidAt = paidAt;
		this.refusedAt = refusedAt;
		this.pendingRefundAt = pendingRefundAt;
		this.refundedAt = refundedAt;
		this.deletedAt = deletedAt;
		this.chargebackAt = chargebackAt;
		this.fullTextIndex = fullTextIndex;
		this.waitingPayment = waitingPayment;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "contribution_id")
	public Integer getContributionId() {
		return this.contributionId;
	}

	public void setContributionId(Integer contributionId) {
		this.contributionId = contributionId;
	}

	@Column(name = "payment_id")
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "reward_id")
	public Integer getRewardId() {
		return this.rewardId;
	}

	public void setRewardId(Integer rewardId) {
		this.rewardId = rewardId;
	}

	@Column(name = "permalink")
	public String getPermalink() {
		return this.permalink;
	}

	public void setPermalink(String permalink) {
		this.permalink = permalink;
	}

	@Column(name = "project_name")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_img")
	public String getProjectImg() {
		return this.projectImg;
	}

	public void setProjectImg(String projectImg) {
		this.projectImg = projectImg;
	}

	@Column(name = "project_online_date", length = 29)
	public Date getProjectOnlineDate() {
		return this.projectOnlineDate;
	}

	public void setProjectOnlineDate(Date projectOnlineDate) {
		this.projectOnlineDate = projectOnlineDate;
	}

	@Column(name = "project_expires_at", length = 29)
	public Date getProjectExpiresAt() {
		return this.projectExpiresAt;
	}

	public void setProjectExpiresAt(Date projectExpiresAt) {
		this.projectExpiresAt = projectExpiresAt;
	}

	@Column(name = "project_state")
	public String getProjectState() {
		return this.projectState;
	}

	public void setProjectState(String projectState) {
		this.projectState = projectState;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_profile_img")
	public String getUserProfileImg() {
		return this.userProfileImg;
	}

	public void setUserProfileImg(String userProfileImg) {
		this.userProfileImg = userProfileImg;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "anonymous")
	public Boolean getAnonymous() {
		return this.anonymous;
	}

	public void setAnonymous(Boolean anonymous) {
		this.anonymous = anonymous;
	}

	@Column(name = "payer_email")
	public String getPayerEmail() {
		return this.payerEmail;
	}

	public void setPayerEmail(String payerEmail) {
		this.payerEmail = payerEmail;
	}

	@Column(name = "key")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value", precision = 131089, scale = 0)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "installments")
	public Integer getInstallments() {
		return this.installments;
	}

	public void setInstallments(Integer installments) {
		this.installments = installments;
	}

	@Column(name = "installment_value", precision = 131089, scale = 0)
	public BigDecimal getInstallmentValue() {
		return this.installmentValue;
	}

	public void setInstallmentValue(BigDecimal installmentValue) {
		this.installmentValue = installmentValue;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "is_second_slip")
	public Boolean getIsSecondSlip() {
		return this.isSecondSlip;
	}

	public void setIsSecondSlip(Boolean isSecondSlip) {
		this.isSecondSlip = isSecondSlip;
	}

	@Column(name = "gateway")
	public String getGateway() {
		return this.gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	@Column(name = "gateway_id")
	public String getGatewayId() {
		return this.gatewayId;
	}

	public void setGatewayId(String gatewayId) {
		this.gatewayId = gatewayId;
	}

	@Column(name = "gateway_fee", precision = 131089, scale = 0)
	public BigDecimal getGatewayFee() {
		return this.gatewayFee;
	}

	public void setGatewayFee(BigDecimal gatewayFee) {
		this.gatewayFee = gatewayFee;
	}

	@Column(name = "gateway_data")
	public Serializable getGatewayData() {
		return this.gatewayData;
	}

	public void setGatewayData(Serializable gatewayData) {
		this.gatewayData = gatewayData;
	}

	@Column(name = "payment_method")
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "pending_at", length = 29)
	public Date getPendingAt() {
		return this.pendingAt;
	}

	public void setPendingAt(Date pendingAt) {
		this.pendingAt = pendingAt;
	}

	@Column(name = "paid_at", length = 29)
	public Date getPaidAt() {
		return this.paidAt;
	}

	public void setPaidAt(Date paidAt) {
		this.paidAt = paidAt;
	}

	@Column(name = "refused_at", length = 29)
	public Date getRefusedAt() {
		return this.refusedAt;
	}

	public void setRefusedAt(Date refusedAt) {
		this.refusedAt = refusedAt;
	}

	@Column(name = "pending_refund_at", length = 29)
	public Date getPendingRefundAt() {
		return this.pendingRefundAt;
	}

	public void setPendingRefundAt(Date pendingRefundAt) {
		this.pendingRefundAt = pendingRefundAt;
	}

	@Column(name = "refunded_at", length = 29)
	public Date getRefundedAt() {
		return this.refundedAt;
	}

	public void setRefundedAt(Date refundedAt) {
		this.refundedAt = refundedAt;
	}

	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "chargeback_at", length = 29)
	public Date getChargebackAt() {
		return this.chargebackAt;
	}

	public void setChargebackAt(Date chargebackAt) {
		this.chargebackAt = chargebackAt;
	}

	@Column(name = "full_text_index")
	public Serializable getFullTextIndex() {
		return this.fullTextIndex;
	}

	public void setFullTextIndex(Serializable fullTextIndex) {
		this.fullTextIndex = fullTextIndex;
	}

	@Column(name = "waiting_payment")
	public Boolean getWaitingPayment() {
		return this.waitingPayment;
	}

	public void setWaitingPayment(Boolean waitingPayment) {
		this.waitingPayment = waitingPayment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContributionDetailsId))
			return false;
		ContributionDetailsId castOther = (ContributionDetailsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getContributionId() == castOther.getContributionId())
						|| (this.getContributionId() != null && castOther.getContributionId() != null
								&& this.getContributionId().equals(castOther.getContributionId())))
				&& ((this.getPaymentId() == castOther.getPaymentId()) || (this.getPaymentId() != null
						&& castOther.getPaymentId() != null && this.getPaymentId().equals(castOther.getPaymentId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getRewardId() == castOther.getRewardId()) || (this.getRewardId() != null
						&& castOther.getRewardId() != null && this.getRewardId().equals(castOther.getRewardId())))
				&& ((this.getPermalink() == castOther.getPermalink()) || (this.getPermalink() != null
						&& castOther.getPermalink() != null && this.getPermalink().equals(castOther.getPermalink())))
				&& ((this.getProjectName() == castOther.getProjectName())
						|| (this.getProjectName() != null && castOther.getProjectName() != null
								&& this.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getProjectImg() == castOther.getProjectImg()) || (this.getProjectImg() != null
						&& castOther.getProjectImg() != null && this.getProjectImg().equals(castOther.getProjectImg())))
				&& ((this.getProjectOnlineDate() == castOther.getProjectOnlineDate())
						|| (this.getProjectOnlineDate() != null && castOther.getProjectOnlineDate() != null
								&& this.getProjectOnlineDate().equals(castOther.getProjectOnlineDate())))
				&& ((this.getProjectExpiresAt() == castOther.getProjectExpiresAt())
						|| (this.getProjectExpiresAt() != null && castOther.getProjectExpiresAt() != null
								&& this.getProjectExpiresAt().equals(castOther.getProjectExpiresAt())))
				&& ((this.getProjectState() == castOther.getProjectState())
						|| (this.getProjectState() != null && castOther.getProjectState() != null
								&& this.getProjectState().equals(castOther.getProjectState())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getUserProfileImg() == castOther.getUserProfileImg())
						|| (this.getUserProfileImg() != null && castOther.getUserProfileImg() != null
								&& this.getUserProfileImg().equals(castOther.getUserProfileImg())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getAnonymous() == castOther.getAnonymous()) || (this.getAnonymous() != null
						&& castOther.getAnonymous() != null && this.getAnonymous().equals(castOther.getAnonymous())))
				&& ((this.getPayerEmail() == castOther.getPayerEmail()) || (this.getPayerEmail() != null
						&& castOther.getPayerEmail() != null && this.getPayerEmail().equals(castOther.getPayerEmail())))
				&& ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null
						&& this.getKey().equals(castOther.getKey())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())))
				&& ((this.getInstallments() == castOther.getInstallments())
						|| (this.getInstallments() != null && castOther.getInstallments() != null
								&& this.getInstallments().equals(castOther.getInstallments())))
				&& ((this.getInstallmentValue() == castOther.getInstallmentValue())
						|| (this.getInstallmentValue() != null && castOther.getInstallmentValue() != null
								&& this.getInstallmentValue().equals(castOther.getInstallmentValue())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getIsSecondSlip() == castOther.getIsSecondSlip())
						|| (this.getIsSecondSlip() != null && castOther.getIsSecondSlip() != null
								&& this.getIsSecondSlip().equals(castOther.getIsSecondSlip())))
				&& ((this.getGateway() == castOther.getGateway()) || (this.getGateway() != null
						&& castOther.getGateway() != null && this.getGateway().equals(castOther.getGateway())))
				&& ((this.getGatewayId() == castOther.getGatewayId()) || (this.getGatewayId() != null
						&& castOther.getGatewayId() != null && this.getGatewayId().equals(castOther.getGatewayId())))
				&& ((this.getGatewayFee() == castOther.getGatewayFee()) || (this.getGatewayFee() != null
						&& castOther.getGatewayFee() != null && this.getGatewayFee().equals(castOther.getGatewayFee())))
				&& ((this.getGatewayData() == castOther.getGatewayData())
						|| (this.getGatewayData() != null && castOther.getGatewayData() != null
								&& this.getGatewayData().equals(castOther.getGatewayData())))
				&& ((this.getPaymentMethod() == castOther.getPaymentMethod())
						|| (this.getPaymentMethod() != null && castOther.getPaymentMethod() != null
								&& this.getPaymentMethod().equals(castOther.getPaymentMethod())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getPendingAt() == castOther.getPendingAt()) || (this.getPendingAt() != null
						&& castOther.getPendingAt() != null && this.getPendingAt().equals(castOther.getPendingAt())))
				&& ((this.getPaidAt() == castOther.getPaidAt()) || (this.getPaidAt() != null
						&& castOther.getPaidAt() != null && this.getPaidAt().equals(castOther.getPaidAt())))
				&& ((this.getRefusedAt() == castOther.getRefusedAt()) || (this.getRefusedAt() != null
						&& castOther.getRefusedAt() != null && this.getRefusedAt().equals(castOther.getRefusedAt())))
				&& ((this.getPendingRefundAt() == castOther.getPendingRefundAt())
						|| (this.getPendingRefundAt() != null && castOther.getPendingRefundAt() != null
								&& this.getPendingRefundAt().equals(castOther.getPendingRefundAt())))
				&& ((this.getRefundedAt() == castOther.getRefundedAt()) || (this.getRefundedAt() != null
						&& castOther.getRefundedAt() != null && this.getRefundedAt().equals(castOther.getRefundedAt())))
				&& ((this.getDeletedAt() == castOther.getDeletedAt()) || (this.getDeletedAt() != null
						&& castOther.getDeletedAt() != null && this.getDeletedAt().equals(castOther.getDeletedAt())))
				&& ((this.getChargebackAt() == castOther.getChargebackAt())
						|| (this.getChargebackAt() != null && castOther.getChargebackAt() != null
								&& this.getChargebackAt().equals(castOther.getChargebackAt())))
				&& ((this.getFullTextIndex() == castOther.getFullTextIndex())
						|| (this.getFullTextIndex() != null && castOther.getFullTextIndex() != null
								&& this.getFullTextIndex().equals(castOther.getFullTextIndex())))
				&& ((this.getWaitingPayment() == castOther.getWaitingPayment())
						|| (this.getWaitingPayment() != null && castOther.getWaitingPayment() != null
								&& this.getWaitingPayment().equals(castOther.getWaitingPayment())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getContributionId() == null ? 0 : this.getContributionId().hashCode());
		result = 37 * result + (getPaymentId() == null ? 0 : this.getPaymentId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getRewardId() == null ? 0 : this.getRewardId().hashCode());
		result = 37 * result + (getPermalink() == null ? 0 : this.getPermalink().hashCode());
		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + (getProjectImg() == null ? 0 : this.getProjectImg().hashCode());
		result = 37 * result + (getProjectOnlineDate() == null ? 0 : this.getProjectOnlineDate().hashCode());
		result = 37 * result + (getProjectExpiresAt() == null ? 0 : this.getProjectExpiresAt().hashCode());
		result = 37 * result + (getProjectState() == null ? 0 : this.getProjectState().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getUserProfileImg() == null ? 0 : this.getUserProfileImg().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getAnonymous() == null ? 0 : this.getAnonymous().hashCode());
		result = 37 * result + (getPayerEmail() == null ? 0 : this.getPayerEmail().hashCode());
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + (getInstallments() == null ? 0 : this.getInstallments().hashCode());
		result = 37 * result + (getInstallmentValue() == null ? 0 : this.getInstallmentValue().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getIsSecondSlip() == null ? 0 : this.getIsSecondSlip().hashCode());
		result = 37 * result + (getGateway() == null ? 0 : this.getGateway().hashCode());
		result = 37 * result + (getGatewayId() == null ? 0 : this.getGatewayId().hashCode());
		result = 37 * result + (getGatewayFee() == null ? 0 : this.getGatewayFee().hashCode());
		result = 37 * result + (getGatewayData() == null ? 0 : this.getGatewayData().hashCode());
		result = 37 * result + (getPaymentMethod() == null ? 0 : this.getPaymentMethod().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getPendingAt() == null ? 0 : this.getPendingAt().hashCode());
		result = 37 * result + (getPaidAt() == null ? 0 : this.getPaidAt().hashCode());
		result = 37 * result + (getRefusedAt() == null ? 0 : this.getRefusedAt().hashCode());
		result = 37 * result + (getPendingRefundAt() == null ? 0 : this.getPendingRefundAt().hashCode());
		result = 37 * result + (getRefundedAt() == null ? 0 : this.getRefundedAt().hashCode());
		result = 37 * result + (getDeletedAt() == null ? 0 : this.getDeletedAt().hashCode());
		result = 37 * result + (getChargebackAt() == null ? 0 : this.getChargebackAt().hashCode());
		result = 37 * result + (getFullTextIndex() == null ? 0 : this.getFullTextIndex().hashCode());
		result = 37 * result + (getWaitingPayment() == null ? 0 : this.getWaitingPayment().hashCode());
		return result;
	}

}
