package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContributionActivitiesId generated by hbm2java
 */
@Embeddable
public class ContributionActivitiesId implements java.io.Serializable {

	private Integer userId;
	private Integer projectId;
	private Serializable elapsedTime;
	private String name;
	private String thumbnail;
	private String projectThumbnail;
	private String projectName;
	private String permalink;

	public ContributionActivitiesId() {
	}

	public ContributionActivitiesId(Integer userId, Integer projectId, Serializable elapsedTime, String name,
			String thumbnail, String projectThumbnail, String projectName, String permalink) {
		this.userId = userId;
		this.projectId = projectId;
		this.elapsedTime = elapsedTime;
		this.name = name;
		this.thumbnail = thumbnail;
		this.projectThumbnail = projectThumbnail;
		this.projectName = projectName;
		this.permalink = permalink;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "elapsed_time")
	public Serializable getElapsedTime() {
		return this.elapsedTime;
	}

	public void setElapsedTime(Serializable elapsedTime) {
		this.elapsedTime = elapsedTime;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "thumbnail")
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	@Column(name = "project_thumbnail")
	public String getProjectThumbnail() {
		return this.projectThumbnail;
	}

	public void setProjectThumbnail(String projectThumbnail) {
		this.projectThumbnail = projectThumbnail;
	}

	@Column(name = "project_name")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "permalink")
	public String getPermalink() {
		return this.permalink;
	}

	public void setPermalink(String permalink) {
		this.permalink = permalink;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContributionActivitiesId))
			return false;
		ContributionActivitiesId castOther = (ContributionActivitiesId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getElapsedTime() == castOther.getElapsedTime())
						|| (this.getElapsedTime() != null && castOther.getElapsedTime() != null
								&& this.getElapsedTime().equals(castOther.getElapsedTime())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getThumbnail() == castOther.getThumbnail()) || (this.getThumbnail() != null
						&& castOther.getThumbnail() != null && this.getThumbnail().equals(castOther.getThumbnail())))
				&& ((this.getProjectThumbnail() == castOther.getProjectThumbnail())
						|| (this.getProjectThumbnail() != null && castOther.getProjectThumbnail() != null
								&& this.getProjectThumbnail().equals(castOther.getProjectThumbnail())))
				&& ((this.getProjectName() == castOther.getProjectName())
						|| (this.getProjectName() != null && castOther.getProjectName() != null
								&& this.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getPermalink() == castOther.getPermalink()) || (this.getPermalink() != null
						&& castOther.getPermalink() != null && this.getPermalink().equals(castOther.getPermalink())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getElapsedTime() == null ? 0 : this.getElapsedTime().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getThumbnail() == null ? 0 : this.getThumbnail().hashCode());
		result = 37 * result + (getProjectThumbnail() == null ? 0 : this.getProjectThumbnail().hashCode());
		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + (getPermalink() == null ? 0 : this.getPermalink().hashCode());
		return result;
	}

}
