package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContributionDetails generated by hbm2java
 */
@Entity
@Table(name = "contribution_details", schema = "1")
public class ContributionDetails implements java.io.Serializable {

	private ContributionDetailsId id;

	public ContributionDetails() {
	}

	public ContributionDetails(ContributionDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "contributionId", column = @Column(name = "contribution_id") ),
			@AttributeOverride(name = "paymentId", column = @Column(name = "payment_id") ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "rewardId", column = @Column(name = "reward_id") ),
			@AttributeOverride(name = "permalink", column = @Column(name = "permalink") ),
			@AttributeOverride(name = "projectName", column = @Column(name = "project_name") ),
			@AttributeOverride(name = "projectImg", column = @Column(name = "project_img") ),
			@AttributeOverride(name = "projectOnlineDate", column = @Column(name = "project_online_date", length = 29) ),
			@AttributeOverride(name = "projectExpiresAt", column = @Column(name = "project_expires_at", length = 29) ),
			@AttributeOverride(name = "projectState", column = @Column(name = "project_state") ),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name") ),
			@AttributeOverride(name = "userProfileImg", column = @Column(name = "user_profile_img") ),
			@AttributeOverride(name = "email", column = @Column(name = "email") ),
			@AttributeOverride(name = "anonymous", column = @Column(name = "anonymous") ),
			@AttributeOverride(name = "payerEmail", column = @Column(name = "payer_email") ),
			@AttributeOverride(name = "key", column = @Column(name = "key") ),
			@AttributeOverride(name = "value", column = @Column(name = "value", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "installments", column = @Column(name = "installments") ),
			@AttributeOverride(name = "installmentValue", column = @Column(name = "installment_value", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ),
			@AttributeOverride(name = "isSecondSlip", column = @Column(name = "is_second_slip") ),
			@AttributeOverride(name = "gateway", column = @Column(name = "gateway") ),
			@AttributeOverride(name = "gatewayId", column = @Column(name = "gateway_id") ),
			@AttributeOverride(name = "gatewayFee", column = @Column(name = "gateway_fee", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "gatewayData", column = @Column(name = "gateway_data") ),
			@AttributeOverride(name = "paymentMethod", column = @Column(name = "payment_method") ),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 29) ),
			@AttributeOverride(name = "pendingAt", column = @Column(name = "pending_at", length = 29) ),
			@AttributeOverride(name = "paidAt", column = @Column(name = "paid_at", length = 29) ),
			@AttributeOverride(name = "refusedAt", column = @Column(name = "refused_at", length = 29) ),
			@AttributeOverride(name = "pendingRefundAt", column = @Column(name = "pending_refund_at", length = 29) ),
			@AttributeOverride(name = "refundedAt", column = @Column(name = "refunded_at", length = 29) ),
			@AttributeOverride(name = "deletedAt", column = @Column(name = "deleted_at", length = 29) ),
			@AttributeOverride(name = "chargebackAt", column = @Column(name = "chargeback_at", length = 29) ),
			@AttributeOverride(name = "fullTextIndex", column = @Column(name = "full_text_index") ),
			@AttributeOverride(name = "waitingPayment", column = @Column(name = "waiting_payment") ) })
	public ContributionDetailsId getId() {
		return this.id;
	}

	public void setId(ContributionDetailsId id) {
		this.id = id;
	}

}
