package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContributionReports generated by hbm2java
 */
@Entity
@Table(name = "contribution_reports", schema = "1")
public class ContributionReports implements java.io.Serializable {

	private ContributionReportsId id;

	public ContributionReports() {
	}

	public ContributionReports(ContributionReportsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "value", column = @Column(name = "value") ),
			@AttributeOverride(name = "minimumValue", column = @Column(name = "minimum_value") ),
			@AttributeOverride(name = "description", column = @Column(name = "description") ),
			@AttributeOverride(name = "gateway", column = @Column(name = "gateway") ),
			@AttributeOverride(name = "acquirerName", column = @Column(name = "acquirer_name") ),
			@AttributeOverride(name = "acquirerTid", column = @Column(name = "acquirer_tid") ),
			@AttributeOverride(name = "paymentMethod", column = @Column(name = "payment_method") ),
			@AttributeOverride(name = "paymentServiceFee", column = @Column(name = "payment_service_fee") ),
			@AttributeOverride(name = "key", column = @Column(name = "key") ),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 13) ),
			@AttributeOverride(name = "confirmedAt", column = @Column(name = "confirmed_at", length = 13) ),
			@AttributeOverride(name = "email", column = @Column(name = "email") ),
			@AttributeOverride(name = "payerEmail", column = @Column(name = "payer_email") ),
			@AttributeOverride(name = "payerName", column = @Column(name = "payer_name") ),
			@AttributeOverride(name = "cpf", column = @Column(name = "cpf") ),
			@AttributeOverride(name = "addressStreet", column = @Column(name = "address_street") ),
			@AttributeOverride(name = "addressComplement", column = @Column(name = "address_complement") ),
			@AttributeOverride(name = "addressNumber", column = @Column(name = "address_number") ),
			@AttributeOverride(name = "addressNeighbourhood", column = @Column(name = "address_neighbourhood") ),
			@AttributeOverride(name = "addressCity", column = @Column(name = "address_city") ),
			@AttributeOverride(name = "addressState", column = @Column(name = "address_state") ),
			@AttributeOverride(name = "addressZipCode", column = @Column(name = "address_zip_code") ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ) })
	public ContributionReportsId getId() {
		return this.id;
	}

	public void setId(ContributionReportsId id) {
		this.id = id;
	}

}
