package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContributionReportsId generated by hbm2java
 */
@Embeddable
public class ContributionReportsId implements java.io.Serializable {

	private Integer projectId;
	private String name;
	private String value;
	private String minimumValue;
	private String description;
	private String gateway;
	private Serializable acquirerName;
	private Serializable acquirerTid;
	private String paymentMethod;
	private String paymentServiceFee;
	private String key;
	private Date createdAt;
	private Date confirmedAt;
	private String email;
	private String payerEmail;
	private String payerName;
	private String cpf;
	private String addressStreet;
	private String addressComplement;
	private String addressNumber;
	private String addressNeighbourhood;
	private String addressCity;
	private String addressState;
	private String addressZipCode;
	private String state;

	public ContributionReportsId() {
	}

	public ContributionReportsId(Integer projectId, String name, String value, String minimumValue, String description,
			String gateway, Serializable acquirerName, Serializable acquirerTid, String paymentMethod,
			String paymentServiceFee, String key, Date createdAt, Date confirmedAt, String email, String payerEmail,
			String payerName, String cpf, String addressStreet, String addressComplement, String addressNumber,
			String addressNeighbourhood, String addressCity, String addressState, String addressZipCode, String state) {
		this.projectId = projectId;
		this.name = name;
		this.value = value;
		this.minimumValue = minimumValue;
		this.description = description;
		this.gateway = gateway;
		this.acquirerName = acquirerName;
		this.acquirerTid = acquirerTid;
		this.paymentMethod = paymentMethod;
		this.paymentServiceFee = paymentServiceFee;
		this.key = key;
		this.createdAt = createdAt;
		this.confirmedAt = confirmedAt;
		this.email = email;
		this.payerEmail = payerEmail;
		this.payerName = payerName;
		this.cpf = cpf;
		this.addressStreet = addressStreet;
		this.addressComplement = addressComplement;
		this.addressNumber = addressNumber;
		this.addressNeighbourhood = addressNeighbourhood;
		this.addressCity = addressCity;
		this.addressState = addressState;
		this.addressZipCode = addressZipCode;
		this.state = state;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "minimum_value")
	public String getMinimumValue() {
		return this.minimumValue;
	}

	public void setMinimumValue(String minimumValue) {
		this.minimumValue = minimumValue;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "gateway")
	public String getGateway() {
		return this.gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	@Column(name = "acquirer_name")
	public Serializable getAcquirerName() {
		return this.acquirerName;
	}

	public void setAcquirerName(Serializable acquirerName) {
		this.acquirerName = acquirerName;
	}

	@Column(name = "acquirer_tid")
	public Serializable getAcquirerTid() {
		return this.acquirerTid;
	}

	public void setAcquirerTid(Serializable acquirerTid) {
		this.acquirerTid = acquirerTid;
	}

	@Column(name = "payment_method")
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "payment_service_fee")
	public String getPaymentServiceFee() {
		return this.paymentServiceFee;
	}

	public void setPaymentServiceFee(String paymentServiceFee) {
		this.paymentServiceFee = paymentServiceFee;
	}

	@Column(name = "key")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "created_at", length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "confirmed_at", length = 13)
	public Date getConfirmedAt() {
		return this.confirmedAt;
	}

	public void setConfirmedAt(Date confirmedAt) {
		this.confirmedAt = confirmedAt;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "payer_email")
	public String getPayerEmail() {
		return this.payerEmail;
	}

	public void setPayerEmail(String payerEmail) {
		this.payerEmail = payerEmail;
	}

	@Column(name = "payer_name")
	public String getPayerName() {
		return this.payerName;
	}

	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	@Column(name = "cpf")
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "address_street")
	public String getAddressStreet() {
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	@Column(name = "address_complement")
	public String getAddressComplement() {
		return this.addressComplement;
	}

	public void setAddressComplement(String addressComplement) {
		this.addressComplement = addressComplement;
	}

	@Column(name = "address_number")
	public String getAddressNumber() {
		return this.addressNumber;
	}

	public void setAddressNumber(String addressNumber) {
		this.addressNumber = addressNumber;
	}

	@Column(name = "address_neighbourhood")
	public String getAddressNeighbourhood() {
		return this.addressNeighbourhood;
	}

	public void setAddressNeighbourhood(String addressNeighbourhood) {
		this.addressNeighbourhood = addressNeighbourhood;
	}

	@Column(name = "address_city")
	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	@Column(name = "address_state")
	public String getAddressState() {
		return this.addressState;
	}

	public void setAddressState(String addressState) {
		this.addressState = addressState;
	}

	@Column(name = "address_zip_code")
	public String getAddressZipCode() {
		return this.addressZipCode;
	}

	public void setAddressZipCode(String addressZipCode) {
		this.addressZipCode = addressZipCode;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContributionReportsId))
			return false;
		ContributionReportsId castOther = (ContributionReportsId) other;

		return ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
				&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())))
				&& ((this.getMinimumValue() == castOther.getMinimumValue())
						|| (this.getMinimumValue() != null && castOther.getMinimumValue() != null
								&& this.getMinimumValue().equals(castOther.getMinimumValue())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getGateway() == castOther.getGateway()) || (this.getGateway() != null
						&& castOther.getGateway() != null && this.getGateway().equals(castOther.getGateway())))
				&& ((this.getAcquirerName() == castOther.getAcquirerName())
						|| (this.getAcquirerName() != null && castOther.getAcquirerName() != null
								&& this.getAcquirerName().equals(castOther.getAcquirerName())))
				&& ((this.getAcquirerTid() == castOther.getAcquirerTid())
						|| (this.getAcquirerTid() != null && castOther.getAcquirerTid() != null
								&& this.getAcquirerTid().equals(castOther.getAcquirerTid())))
				&& ((this.getPaymentMethod() == castOther.getPaymentMethod())
						|| (this.getPaymentMethod() != null && castOther.getPaymentMethod() != null
								&& this.getPaymentMethod().equals(castOther.getPaymentMethod())))
				&& ((this.getPaymentServiceFee() == castOther.getPaymentServiceFee())
						|| (this.getPaymentServiceFee() != null && castOther.getPaymentServiceFee() != null
								&& this.getPaymentServiceFee().equals(castOther.getPaymentServiceFee())))
				&& ((this.getKey() == castOther.getKey()) || (this.getKey() != null && castOther.getKey() != null
						&& this.getKey().equals(castOther.getKey())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getConfirmedAt() == castOther.getConfirmedAt())
						|| (this.getConfirmedAt() != null && castOther.getConfirmedAt() != null
								&& this.getConfirmedAt().equals(castOther.getConfirmedAt())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getPayerEmail() == castOther.getPayerEmail()) || (this.getPayerEmail() != null
						&& castOther.getPayerEmail() != null && this.getPayerEmail().equals(castOther.getPayerEmail())))
				&& ((this.getPayerName() == castOther.getPayerName()) || (this.getPayerName() != null
						&& castOther.getPayerName() != null && this.getPayerName().equals(castOther.getPayerName())))
				&& ((this.getCpf() == castOther.getCpf()) || (this.getCpf() != null && castOther.getCpf() != null
						&& this.getCpf().equals(castOther.getCpf())))
				&& ((this.getAddressStreet() == castOther.getAddressStreet())
						|| (this.getAddressStreet() != null && castOther.getAddressStreet() != null
								&& this.getAddressStreet().equals(castOther.getAddressStreet())))
				&& ((this.getAddressComplement() == castOther.getAddressComplement())
						|| (this.getAddressComplement() != null && castOther.getAddressComplement() != null
								&& this.getAddressComplement().equals(castOther.getAddressComplement())))
				&& ((this.getAddressNumber() == castOther.getAddressNumber())
						|| (this.getAddressNumber() != null && castOther.getAddressNumber() != null
								&& this.getAddressNumber().equals(castOther.getAddressNumber())))
				&& ((this.getAddressNeighbourhood() == castOther.getAddressNeighbourhood())
						|| (this.getAddressNeighbourhood() != null && castOther.getAddressNeighbourhood() != null
								&& this.getAddressNeighbourhood().equals(castOther.getAddressNeighbourhood())))
				&& ((this.getAddressCity() == castOther.getAddressCity())
						|| (this.getAddressCity() != null && castOther.getAddressCity() != null
								&& this.getAddressCity().equals(castOther.getAddressCity())))
				&& ((this.getAddressState() == castOther.getAddressState())
						|| (this.getAddressState() != null && castOther.getAddressState() != null
								&& this.getAddressState().equals(castOther.getAddressState())))
				&& ((this.getAddressZipCode() == castOther.getAddressZipCode())
						|| (this.getAddressZipCode() != null && castOther.getAddressZipCode() != null
								&& this.getAddressZipCode().equals(castOther.getAddressZipCode())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + (getMinimumValue() == null ? 0 : this.getMinimumValue().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getGateway() == null ? 0 : this.getGateway().hashCode());
		result = 37 * result + (getAcquirerName() == null ? 0 : this.getAcquirerName().hashCode());
		result = 37 * result + (getAcquirerTid() == null ? 0 : this.getAcquirerTid().hashCode());
		result = 37 * result + (getPaymentMethod() == null ? 0 : this.getPaymentMethod().hashCode());
		result = 37 * result + (getPaymentServiceFee() == null ? 0 : this.getPaymentServiceFee().hashCode());
		result = 37 * result + (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getConfirmedAt() == null ? 0 : this.getConfirmedAt().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getPayerEmail() == null ? 0 : this.getPayerEmail().hashCode());
		result = 37 * result + (getPayerName() == null ? 0 : this.getPayerName().hashCode());
		result = 37 * result + (getCpf() == null ? 0 : this.getCpf().hashCode());
		result = 37 * result + (getAddressStreet() == null ? 0 : this.getAddressStreet().hashCode());
		result = 37 * result + (getAddressComplement() == null ? 0 : this.getAddressComplement().hashCode());
		result = 37 * result + (getAddressNumber() == null ? 0 : this.getAddressNumber().hashCode());
		result = 37 * result + (getAddressNeighbourhood() == null ? 0 : this.getAddressNeighbourhood().hashCode());
		result = 37 * result + (getAddressCity() == null ? 0 : this.getAddressCity().hashCode());
		result = 37 * result + (getAddressState() == null ? 0 : this.getAddressState().hashCode());
		result = 37 * result + (getAddressZipCode() == null ? 0 : this.getAddressZipCode().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		return result;
	}

}
