package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Notifications generated by hbm2java
 */
@Entity
@Table(name = "notifications", schema = "1")
public class Notifications implements java.io.Serializable {

	private NotificationsId id;

	public Notifications() {
	}

	public Notifications(NotificationsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "origin", column = @Column(name = "origin") ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name") ),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 29) ),
			@AttributeOverride(name = "sentAt", column = @Column(name = "sent_at", length = 29) ),
			@AttributeOverride(name = "deliverAt", column = @Column(name = "deliver_at", length = 29) ) })
	public NotificationsId getId() {
		return this.id;
	}

	public void setId(NotificationsId id) {
		this.id = id;
	}

}
