package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectReminders generated by hbm2java
 */
@Entity
@Table(name = "project_reminders", schema = "1")
public class ProjectReminders implements java.io.Serializable {

	private ProjectRemindersId id;

	public ProjectReminders() {
	}

	public ProjectReminders(ProjectRemindersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id") ) })
	public ProjectRemindersId getId() {
		return this.id;
	}

	public void setId(ProjectRemindersId id) {
		this.id = id;
	}

}
