package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectAccountErrors generated by hbm2java
 */
@Entity
@Table(name = "project_account_errors", schema = "1")
public class ProjectAccountErrors implements java.io.Serializable {

	private ProjectAccountErrorsId id;

	public ProjectAccountErrors() {
	}

	public ProjectAccountErrors(ProjectAccountErrorsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "projectAccountId", column = @Column(name = "project_account_id") ),
			@AttributeOverride(name = "reason", column = @Column(name = "reason") ),
			@AttributeOverride(name = "solved", column = @Column(name = "solved") ),
			@AttributeOverride(name = "zoneTimestamp", column = @Column(name = "zone_timestamp", length = 29) ),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 29) ) })
	public ProjectAccountErrorsId getId() {
		return this.id;
	}

	public void setId(ProjectAccountErrorsId id) {
		this.id = id;
	}

}
