package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectTotals generated by hbm2java
 */
@Entity
@Table(name = "project_totals", schema = "1")
public class ProjectTotals implements java.io.Serializable {

	private ProjectTotalsId id;

	public ProjectTotals() {
	}

	public ProjectTotals(ProjectTotalsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "pledged", column = @Column(name = "pledged", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "paidPledged", column = @Column(name = "paid_pledged", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "progress", column = @Column(name = "progress", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "totalPaymentServiceFee", column = @Column(name = "total_payment_service_fee", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "paidTotalPaymentServiceFee", column = @Column(name = "paid_total_payment_service_fee", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "totalContributions", column = @Column(name = "total_contributions") ),
			@AttributeOverride(name = "totalContributors", column = @Column(name = "total_contributors") ) })
	public ProjectTotalsId getId() {
		return this.id;
	}

	public void setId(ProjectTotalsId id) {
		this.id = id;
	}

}
