package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectPostsDetails generated by hbm2java
 */
@Entity
@Table(name = "project_posts_details", schema = "1")
public class ProjectPostsDetails implements java.io.Serializable {

	private ProjectPostsDetailsId id;

	public ProjectPostsDetails() {
	}

	public ProjectPostsDetails(ProjectPostsDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "isOwnerOrAdmin", column = @Column(name = "is_owner_or_admin") ),
			@AttributeOverride(name = "exclusive", column = @Column(name = "exclusive") ),
			@AttributeOverride(name = "title", column = @Column(name = "title") ),
			@AttributeOverride(name = "commentHtml", column = @Column(name = "comment_html") ),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 29) ) })
	public ProjectPostsDetailsId getId() {
		return this.id;
	}

	public void setId(ProjectPostsDetailsId id) {
		this.id = id;
	}

}
