package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectDetails generated by hbm2java
 */
@Entity
@Table(name = "project_details", schema = "1")
public class ProjectDetails implements java.io.Serializable {

	private ProjectDetailsId id;

	public ProjectDetails() {
	}

	public ProjectDetails(ProjectDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "headline", column = @Column(name = "headline") ),
			@AttributeOverride(name = "budget", column = @Column(name = "budget") ),
			@AttributeOverride(name = "goal", column = @Column(name = "goal", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "aboutHtml", column = @Column(name = "about_html") ),
			@AttributeOverride(name = "permalink", column = @Column(name = "permalink") ),
			@AttributeOverride(name = "videoEmbedUrl", column = @Column(name = "video_embed_url") ),
			@AttributeOverride(name = "videoUrl", column = @Column(name = "video_url") ),
			@AttributeOverride(name = "categoryName", column = @Column(name = "category_name") ),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id") ),
			@AttributeOverride(name = "originalImage", column = @Column(name = "original_image") ),
			@AttributeOverride(name = "thumbImage", column = @Column(name = "thumb_image") ),
			@AttributeOverride(name = "smallImage", column = @Column(name = "small_image") ),
			@AttributeOverride(name = "largeImage", column = @Column(name = "large_image") ),
			@AttributeOverride(name = "videoCoverImage", column = @Column(name = "video_cover_image") ),
			@AttributeOverride(name = "progress", column = @Column(name = "progress", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "pledged", column = @Column(name = "pledged", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "totalContributions", column = @Column(name = "total_contributions") ),
			@AttributeOverride(name = "totalContributors", column = @Column(name = "total_contributors") ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ),
			@AttributeOverride(name = "mode", column = @Column(name = "mode") ),
			@AttributeOverride(name = "stateOrder", column = @Column(name = "state_order") ),
			@AttributeOverride(name = "expiresAt", column = @Column(name = "expires_at", length = 29) ),
			@AttributeOverride(name = "zoneExpiresAt", column = @Column(name = "zone_expires_at", length = 29) ),
			@AttributeOverride(name = "onlineDate", column = @Column(name = "online_date", length = 29) ),
			@AttributeOverride(name = "zoneOnlineDate", column = @Column(name = "zone_online_date", length = 29) ),
			@AttributeOverride(name = "sentToAnalysisAt", column = @Column(name = "sent_to_analysis_at", length = 29) ),
			@AttributeOverride(name = "isPublished", column = @Column(name = "is_published") ),
			@AttributeOverride(name = "isExpired", column = @Column(name = "is_expired") ),
			@AttributeOverride(name = "openForContributions", column = @Column(name = "open_for_contributions") ),
			@AttributeOverride(name = "onlineDays", column = @Column(name = "online_days") ),
			@AttributeOverride(name = "remainingTime", column = @Column(name = "remaining_time") ),
			@AttributeOverride(name = "elapsedTime", column = @Column(name = "elapsed_time") ),
			@AttributeOverride(name = "postsCount", column = @Column(name = "posts_count") ),
			@AttributeOverride(name = "address", column = @Column(name = "address") ),
			@AttributeOverride(name = "user", column = @Column(name = "user") ),
			@AttributeOverride(name = "reminderCount", column = @Column(name = "reminder_count") ),
			@AttributeOverride(name = "isOwnerOrAdmin", column = @Column(name = "is_owner_or_admin") ),
			@AttributeOverride(name = "userSignedIn", column = @Column(name = "user_signed_in") ),
			@AttributeOverride(name = "inReminder", column = @Column(name = "in_reminder") ),
			@AttributeOverride(name = "totalPosts", column = @Column(name = "total_posts") ),
			@AttributeOverride(name = "isAdminRole", column = @Column(name = "is_admin_role") ) })
	public ProjectDetailsId getId() {
		return this.id;
	}

	public void setId(ProjectDetailsId id) {
		this.id = id;
	}

}
