package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectScores generated by hbm2java
 */
@Entity
@Table(name = "project_scores", schema = "1")
public class ProjectScores implements java.io.Serializable {

	private ProjectScoresId id;

	public ProjectScores() {
	}

	public ProjectScores(ProjectScoresId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "score", column = @Column(name = "score", precision = 131089, scale = 0) ) })
	public ProjectScoresId getId() {
		return this.id;
	}

	public void setId(ProjectScoresId id) {
		this.id = id;
	}

}
