package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReferralTotalsId generated by hbm2java
 */
@Embeddable
public class ReferralTotalsId implements java.io.Serializable {

	private String month;
	private String referralLink;
	private String permalink;
	private Long contributions;
	private Long confirmedContributions;
	private BigDecimal confirmedValue;

	public ReferralTotalsId() {
	}

	public ReferralTotalsId(String month, String referralLink, String permalink, Long contributions,
			Long confirmedContributions, BigDecimal confirmedValue) {
		this.month = month;
		this.referralLink = referralLink;
		this.permalink = permalink;
		this.contributions = contributions;
		this.confirmedContributions = confirmedContributions;
		this.confirmedValue = confirmedValue;
	}

	@Column(name = "month")
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "referral_link")
	public String getReferralLink() {
		return this.referralLink;
	}

	public void setReferralLink(String referralLink) {
		this.referralLink = referralLink;
	}

	@Column(name = "permalink")
	public String getPermalink() {
		return this.permalink;
	}

	public void setPermalink(String permalink) {
		this.permalink = permalink;
	}

	@Column(name = "contributions")
	public Long getContributions() {
		return this.contributions;
	}

	public void setContributions(Long contributions) {
		this.contributions = contributions;
	}

	@Column(name = "confirmed_contributions")
	public Long getConfirmedContributions() {
		return this.confirmedContributions;
	}

	public void setConfirmedContributions(Long confirmedContributions) {
		this.confirmedContributions = confirmedContributions;
	}

	@Column(name = "confirmed_value", precision = 131089, scale = 0)
	public BigDecimal getConfirmedValue() {
		return this.confirmedValue;
	}

	public void setConfirmedValue(BigDecimal confirmedValue) {
		this.confirmedValue = confirmedValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReferralTotalsId))
			return false;
		ReferralTotalsId castOther = (ReferralTotalsId) other;

		return ((this.getMonth() == castOther.getMonth()) || (this.getMonth() != null && castOther.getMonth() != null
				&& this.getMonth().equals(castOther.getMonth())))
				&& ((this.getReferralLink() == castOther.getReferralLink())
						|| (this.getReferralLink() != null && castOther.getReferralLink() != null
								&& this.getReferralLink().equals(castOther.getReferralLink())))
				&& ((this.getPermalink() == castOther.getPermalink()) || (this.getPermalink() != null
						&& castOther.getPermalink() != null && this.getPermalink().equals(castOther.getPermalink())))
				&& ((this.getContributions() == castOther.getContributions())
						|| (this.getContributions() != null && castOther.getContributions() != null
								&& this.getContributions().equals(castOther.getContributions())))
				&& ((this.getConfirmedContributions() == castOther.getConfirmedContributions())
						|| (this.getConfirmedContributions() != null && castOther.getConfirmedContributions() != null
								&& this.getConfirmedContributions().equals(castOther.getConfirmedContributions())))
				&& ((this.getConfirmedValue() == castOther.getConfirmedValue())
						|| (this.getConfirmedValue() != null && castOther.getConfirmedValue() != null
								&& this.getConfirmedValue().equals(castOther.getConfirmedValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMonth() == null ? 0 : this.getMonth().hashCode());
		result = 37 * result + (getReferralLink() == null ? 0 : this.getReferralLink().hashCode());
		result = 37 * result + (getPermalink() == null ? 0 : this.getPermalink().hashCode());
		result = 37 * result + (getContributions() == null ? 0 : this.getContributions().hashCode());
		result = 37 * result + (getConfirmedContributions() == null ? 0 : this.getConfirmedContributions().hashCode());
		result = 37 * result + (getConfirmedValue() == null ? 0 : this.getConfirmedValue().hashCode());
		return result;
	}

}
