package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ReferralTotals generated by hbm2java
 */
@Entity
@Table(name = "referral_totals", schema = "1")
public class ReferralTotals implements java.io.Serializable {

	private ReferralTotalsId id;

	public ReferralTotals() {
	}

	public ReferralTotals(ReferralTotalsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "month", column = @Column(name = "month") ),
			@AttributeOverride(name = "referralLink", column = @Column(name = "referral_link") ),
			@AttributeOverride(name = "permalink", column = @Column(name = "permalink") ),
			@AttributeOverride(name = "contributions", column = @Column(name = "contributions") ),
			@AttributeOverride(name = "confirmedContributions", column = @Column(name = "confirmed_contributions") ),
			@AttributeOverride(name = "confirmedValue", column = @Column(name = "confirmed_value", precision = 131089, scale = 0) ) })
	public ReferralTotalsId getId() {
		return this.id;
	}

	public void setId(ReferralTotalsId id) {
		this.id = id;
	}

}
