package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RewardDetails generated by hbm2java
 */
@Entity
@Table(name = "reward_details", schema = "1")
public class RewardDetails implements java.io.Serializable {

	private RewardDetailsId id;

	public RewardDetails() {
	}

	public RewardDetails(RewardDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "description", column = @Column(name = "description") ),
			@AttributeOverride(name = "minimumValue", column = @Column(name = "minimum_value", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "maximumContributions", column = @Column(name = "maximum_contributions") ),
			@AttributeOverride(name = "deliverAt", column = @Column(name = "deliver_at", length = 29) ),
			@AttributeOverride(name = "updatedAt", column = @Column(name = "updated_at", length = 29) ),
			@AttributeOverride(name = "paidCount", column = @Column(name = "paid_count") ),
			@AttributeOverride(name = "waitingPaymentCount", column = @Column(name = "waiting_payment_count") ) })
	public RewardDetailsId getId() {
		return this.id;
	}

	public void setId(RewardDetailsId id) {
		this.id = id;
	}

}
