package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RewardDetailsId generated by hbm2java
 */
@Embeddable
public class RewardDetailsId implements java.io.Serializable {

	private Integer id;
	private Integer projectId;
	private String description;
	private BigDecimal minimumValue;
	private Integer maximumContributions;
	private Date deliverAt;
	private Date updatedAt;
	private Long paidCount;
	private Long waitingPaymentCount;

	public RewardDetailsId() {
	}

	public RewardDetailsId(Integer id, Integer projectId, String description, BigDecimal minimumValue,
			Integer maximumContributions, Date deliverAt, Date updatedAt, Long paidCount, Long waitingPaymentCount) {
		this.id = id;
		this.projectId = projectId;
		this.description = description;
		this.minimumValue = minimumValue;
		this.maximumContributions = maximumContributions;
		this.deliverAt = deliverAt;
		this.updatedAt = updatedAt;
		this.paidCount = paidCount;
		this.waitingPaymentCount = waitingPaymentCount;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "minimum_value", precision = 131089, scale = 0)
	public BigDecimal getMinimumValue() {
		return this.minimumValue;
	}

	public void setMinimumValue(BigDecimal minimumValue) {
		this.minimumValue = minimumValue;
	}

	@Column(name = "maximum_contributions")
	public Integer getMaximumContributions() {
		return this.maximumContributions;
	}

	public void setMaximumContributions(Integer maximumContributions) {
		this.maximumContributions = maximumContributions;
	}

	@Column(name = "deliver_at", length = 29)
	public Date getDeliverAt() {
		return this.deliverAt;
	}

	public void setDeliverAt(Date deliverAt) {
		this.deliverAt = deliverAt;
	}

	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "paid_count")
	public Long getPaidCount() {
		return this.paidCount;
	}

	public void setPaidCount(Long paidCount) {
		this.paidCount = paidCount;
	}

	@Column(name = "waiting_payment_count")
	public Long getWaitingPaymentCount() {
		return this.waitingPaymentCount;
	}

	public void setWaitingPaymentCount(Long waitingPaymentCount) {
		this.waitingPaymentCount = waitingPaymentCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RewardDetailsId))
			return false;
		RewardDetailsId castOther = (RewardDetailsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getMinimumValue() == castOther.getMinimumValue())
						|| (this.getMinimumValue() != null && castOther.getMinimumValue() != null
								&& this.getMinimumValue().equals(castOther.getMinimumValue())))
				&& ((this.getMaximumContributions() == castOther.getMaximumContributions())
						|| (this.getMaximumContributions() != null && castOther.getMaximumContributions() != null
								&& this.getMaximumContributions().equals(castOther.getMaximumContributions())))
				&& ((this.getDeliverAt() == castOther.getDeliverAt()) || (this.getDeliverAt() != null
						&& castOther.getDeliverAt() != null && this.getDeliverAt().equals(castOther.getDeliverAt())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getPaidCount() == castOther.getPaidCount()) || (this.getPaidCount() != null
						&& castOther.getPaidCount() != null && this.getPaidCount().equals(castOther.getPaidCount())))
				&& ((this.getWaitingPaymentCount() == castOther.getWaitingPaymentCount())
						|| (this.getWaitingPaymentCount() != null && castOther.getWaitingPaymentCount() != null
								&& this.getWaitingPaymentCount().equals(castOther.getWaitingPaymentCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getMinimumValue() == null ? 0 : this.getMinimumValue().hashCode());
		result = 37 * result + (getMaximumContributions() == null ? 0 : this.getMaximumContributions().hashCode());
		result = 37 * result + (getDeliverAt() == null ? 0 : this.getDeliverAt().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getPaidCount() == null ? 0 : this.getPaidCount().hashCode());
		result = 37 * result + (getWaitingPaymentCount() == null ? 0 : this.getWaitingPaymentCount().hashCode());
		return result;
	}

}
