package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeamMembersId generated by hbm2java
 */
@Embeddable
public class TeamMembersId implements java.io.Serializable {

	private Integer id;
	private String name;
	private String img;
	private Long totalContributedProjects;
	private BigDecimal totalAmountContributed;

	public TeamMembersId() {
	}

	public TeamMembersId(Integer id, String name, String img, Long totalContributedProjects,
			BigDecimal totalAmountContributed) {
		this.id = id;
		this.name = name;
		this.img = img;
		this.totalContributedProjects = totalContributedProjects;
		this.totalAmountContributed = totalAmountContributed;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "img")
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "total_contributed_projects")
	public Long getTotalContributedProjects() {
		return this.totalContributedProjects;
	}

	public void setTotalContributedProjects(Long totalContributedProjects) {
		this.totalContributedProjects = totalContributedProjects;
	}

	@Column(name = "total_amount_contributed", precision = 131089, scale = 0)
	public BigDecimal getTotalAmountContributed() {
		return this.totalAmountContributed;
	}

	public void setTotalAmountContributed(BigDecimal totalAmountContributed) {
		this.totalAmountContributed = totalAmountContributed;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeamMembersId))
			return false;
		TeamMembersId castOther = (TeamMembersId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getImg() == castOther.getImg()) || (this.getImg() != null && castOther.getImg() != null
						&& this.getImg().equals(castOther.getImg())))
				&& ((this.getTotalContributedProjects() == castOther.getTotalContributedProjects())
						|| (this.getTotalContributedProjects() != null
								&& castOther.getTotalContributedProjects() != null
								&& this.getTotalContributedProjects().equals(castOther.getTotalContributedProjects())))
				&& ((this.getTotalAmountContributed() == castOther.getTotalAmountContributed())
						|| (this.getTotalAmountContributed() != null && castOther.getTotalAmountContributed() != null
								&& this.getTotalAmountContributed().equals(castOther.getTotalAmountContributed())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getImg() == null ? 0 : this.getImg().hashCode());
		result = 37 * result
				+ (getTotalContributedProjects() == null ? 0 : this.getTotalContributedProjects().hashCode());
		result = 37 * result + (getTotalAmountContributed() == null ? 0 : this.getTotalAmountContributed().hashCode());
		return result;
	}

}
