package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details", schema = "1")
public class UserDetails implements java.io.Serializable {

	private UserDetailsId id;

	public UserDetails() {
	}

	public UserDetails(UserDetailsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "addressCity", column = @Column(name = "address_city") ),
			@AttributeOverride(name = "deactivatedAt", column = @Column(name = "deactivated_at", length = 29) ),
			@AttributeOverride(name = "profileImgThumbnail", column = @Column(name = "profile_img_thumbnail") ),
			@AttributeOverride(name = "facebookLink", column = @Column(name = "facebook_link") ),
			@AttributeOverride(name = "twitterUsername", column = @Column(name = "twitter_username") ),
			@AttributeOverride(name = "email", column = @Column(name = "email") ),
			@AttributeOverride(name = "totalContributedProjects", column = @Column(name = "total_contributed_projects") ),
			@AttributeOverride(name = "totalPublishedProjects", column = @Column(name = "total_published_projects") ),
			@AttributeOverride(name = "links", column = @Column(name = "links") ) })
	public UserDetailsId getId() {
		return this.id;
	}

	public void setId(UserDetailsId id) {
		this.id = id;
	}

}
