package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "1")
public class Users implements java.io.Serializable {

	private UsersId id;

	public Users() {
	}

	public Users(UsersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "profileImgThumbnail", column = @Column(name = "profile_img_thumbnail") ),
			@AttributeOverride(name = "facebookLink", column = @Column(name = "facebook_link") ),
			@AttributeOverride(name = "twitterUsername", column = @Column(name = "twitter_username") ),
			@AttributeOverride(name = "email", column = @Column(name = "email") ),
			@AttributeOverride(name = "deactivatedAt", column = @Column(name = "deactivated_at", length = 29) ),
			@AttributeOverride(name = "fullTextIndex", column = @Column(name = "full_text_index") ) })
	public UsersId getId() {
		return this.id;
	}

	public void setId(UsersId id) {
		this.id = id;
	}

}
