package src;
// Generated 13 Jun, 2016 5:39:40 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserFriends generated by hbm2java
 */
@Entity
@Table(name = "user_friends", schema = "1")
public class UserFriends implements java.io.Serializable {

	private UserFriendsId id;

	public UserFriends() {
	}

	public UserFriends(UserFriendsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "friendId", column = @Column(name = "friend_id") ),
			@AttributeOverride(name = "following", column = @Column(name = "following") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "avatar", column = @Column(name = "avatar") ),
			@AttributeOverride(name = "totalContributedProjects", column = @Column(name = "total_contributed_projects") ),
			@AttributeOverride(name = "totalPublishedProjects", column = @Column(name = "total_published_projects") ),
			@AttributeOverride(name = "city", column = @Column(name = "city") ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ) })
	public UserFriendsId getId() {
		return this.id;
	}

	public void setId(UserFriendsId id) {
		this.id = id;
	}

}
