package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Balances generated by hbm2java
 */
@Entity
@Table(name = "balances", schema = "1")
public class Balances implements java.io.Serializable {

	private BalancesId id;

	public Balances() {
	}

	public Balances(BalancesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", precision = 131089, scale = 0) ) })
	public BalancesId getId() {
		return this.id;
	}

	public void setId(BalancesId id) {
		this.id = id;
	}

}
