package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BankAccounts generated by hbm2java
 */
@Entity
@Table(name = "bank_accounts", schema = "1")
public class BankAccounts implements java.io.Serializable {

	private BankAccountsId id;

	public BankAccounts() {
	}

	public BankAccounts(BankAccountsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "bankName", column = @Column(name = "bank_name") ),
			@AttributeOverride(name = "bankCode", column = @Column(name = "bank_code") ),
			@AttributeOverride(name = "account", column = @Column(name = "account") ),
			@AttributeOverride(name = "accountDigit", column = @Column(name = "account_digit") ),
			@AttributeOverride(name = "agency", column = @Column(name = "agency") ),
			@AttributeOverride(name = "agencyDigit", column = @Column(name = "agency_digit") ),
			@AttributeOverride(name = "ownerName", column = @Column(name = "owner_name") ),
			@AttributeOverride(name = "ownerDocument", column = @Column(name = "owner_document") ),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 29) ),
			@AttributeOverride(name = "updatedAt", column = @Column(name = "updated_at", length = 29) ) })
	public BankAccountsId getId() {
		return this.id;
	}

	public void setId(BankAccountsId id) {
		this.id = id;
	}

}
