package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CategoryFollowers generated by hbm2java
 */
@Entity
@Table(name = "category_followers", schema = "1")
public class CategoryFollowers implements java.io.Serializable {

	private CategoryFollowersId id;

	public CategoryFollowers() {
	}

	public CategoryFollowers(CategoryFollowersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "categoryId", column = @Column(name = "category_id") ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id") ) })
	public CategoryFollowersId getId() {
		return this.id;
	}

	public void setId(CategoryFollowersId id) {
		this.id = id;
	}

}
