package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContributionActivities generated by hbm2java
 */
@Entity
@Table(name = "contribution_activities", schema = "1")
public class ContributionActivities implements java.io.Serializable {

	private ContributionActivitiesId id;

	public ContributionActivities() {
	}

	public ContributionActivities(ContributionActivitiesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "elapsedTime", column = @Column(name = "elapsed_time") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "thumbnail", column = @Column(name = "thumbnail") ),
			@AttributeOverride(name = "projectThumbnail", column = @Column(name = "project_thumbnail") ),
			@AttributeOverride(name = "projectName", column = @Column(name = "project_name") ),
			@AttributeOverride(name = "permalink", column = @Column(name = "permalink") ) })
	public ContributionActivitiesId getId() {
		return this.id;
	}

	public void setId(ContributionActivitiesId id) {
		this.id = id;
	}

}
