package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DirectMessages generated by hbm2java
 */
@Entity
@Table(name = "direct_messages", schema = "1")
public class DirectMessages implements java.io.Serializable {

	private DirectMessagesId id;

	public DirectMessages() {
	}

	public DirectMessages(DirectMessagesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "toUserId", column = @Column(name = "to_user_id") ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "fromEmail", column = @Column(name = "from_email") ),
			@AttributeOverride(name = "fromName", column = @Column(name = "from_name") ),
			@AttributeOverride(name = "content", column = @Column(name = "content") ) })
	public DirectMessagesId getId() {
		return this.id;
	}

	public void setId(DirectMessagesId id) {
		this.id = id;
	}

}
