package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectContributionsId generated by hbm2java
 */
@Embeddable
public class ProjectContributionsId implements java.io.Serializable {

	private Boolean anonymous;
	private Integer projectId;
	private BigDecimal rewardId;
	private BigDecimal id;
	private String profileImgThumbnail;
	private Integer userId;
	private String userName;
	private BigDecimal value;
	private String state;
	private String email;
	private Serializable reward;
	private Boolean waitingPayment;
	private Boolean isOwnerOrAdmin;
	private Long totalContributedProjects;
	private Date createdAt;
	private Boolean hasAnother;
	private Serializable fullTextIndex;

	public ProjectContributionsId() {
	}

	public ProjectContributionsId(Boolean anonymous, Integer projectId, BigDecimal rewardId, BigDecimal id,
			String profileImgThumbnail, Integer userId, String userName, BigDecimal value, String state, String email,
			Serializable reward, Boolean waitingPayment, Boolean isOwnerOrAdmin, Long totalContributedProjects,
			Date createdAt, Boolean hasAnother, Serializable fullTextIndex) {
		this.anonymous = anonymous;
		this.projectId = projectId;
		this.rewardId = rewardId;
		this.id = id;
		this.profileImgThumbnail = profileImgThumbnail;
		this.userId = userId;
		this.userName = userName;
		this.value = value;
		this.state = state;
		this.email = email;
		this.reward = reward;
		this.waitingPayment = waitingPayment;
		this.isOwnerOrAdmin = isOwnerOrAdmin;
		this.totalContributedProjects = totalContributedProjects;
		this.createdAt = createdAt;
		this.hasAnother = hasAnother;
		this.fullTextIndex = fullTextIndex;
	}

	@Column(name = "anonymous")
	public Boolean getAnonymous() {
		return this.anonymous;
	}

	public void setAnonymous(Boolean anonymous) {
		this.anonymous = anonymous;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "reward_id", precision = 131089, scale = 0)
	public BigDecimal getRewardId() {
		return this.rewardId;
	}

	public void setRewardId(BigDecimal rewardId) {
		this.rewardId = rewardId;
	}

	@Column(name = "id", precision = 131089, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "profile_img_thumbnail")
	public String getProfileImgThumbnail() {
		return this.profileImgThumbnail;
	}

	public void setProfileImgThumbnail(String profileImgThumbnail) {
		this.profileImgThumbnail = profileImgThumbnail;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "value", precision = 131089, scale = 0)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "reward")
	public Serializable getReward() {
		return this.reward;
	}

	public void setReward(Serializable reward) {
		this.reward = reward;
	}

	@Column(name = "waiting_payment")
	public Boolean getWaitingPayment() {
		return this.waitingPayment;
	}

	public void setWaitingPayment(Boolean waitingPayment) {
		this.waitingPayment = waitingPayment;
	}

	@Column(name = "is_owner_or_admin")
	public Boolean getIsOwnerOrAdmin() {
		return this.isOwnerOrAdmin;
	}

	public void setIsOwnerOrAdmin(Boolean isOwnerOrAdmin) {
		this.isOwnerOrAdmin = isOwnerOrAdmin;
	}

	@Column(name = "total_contributed_projects")
	public Long getTotalContributedProjects() {
		return this.totalContributedProjects;
	}

	public void setTotalContributedProjects(Long totalContributedProjects) {
		this.totalContributedProjects = totalContributedProjects;
	}

	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "has_another")
	public Boolean getHasAnother() {
		return this.hasAnother;
	}

	public void setHasAnother(Boolean hasAnother) {
		this.hasAnother = hasAnother;
	}

	@Column(name = "full_text_index")
	public Serializable getFullTextIndex() {
		return this.fullTextIndex;
	}

	public void setFullTextIndex(Serializable fullTextIndex) {
		this.fullTextIndex = fullTextIndex;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectContributionsId))
			return false;
		ProjectContributionsId castOther = (ProjectContributionsId) other;

		return ((this.getAnonymous() == castOther.getAnonymous()) || (this.getAnonymous() != null
				&& castOther.getAnonymous() != null && this.getAnonymous().equals(castOther.getAnonymous())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getRewardId() == castOther.getRewardId()) || (this.getRewardId() != null
						&& castOther.getRewardId() != null && this.getRewardId().equals(castOther.getRewardId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getProfileImgThumbnail() == castOther.getProfileImgThumbnail())
						|| (this.getProfileImgThumbnail() != null && castOther.getProfileImgThumbnail() != null
								&& this.getProfileImgThumbnail().equals(castOther.getProfileImgThumbnail())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getReward() == castOther.getReward()) || (this.getReward() != null
						&& castOther.getReward() != null && this.getReward().equals(castOther.getReward())))
				&& ((this.getWaitingPayment() == castOther.getWaitingPayment())
						|| (this.getWaitingPayment() != null && castOther.getWaitingPayment() != null
								&& this.getWaitingPayment().equals(castOther.getWaitingPayment())))
				&& ((this.getIsOwnerOrAdmin() == castOther.getIsOwnerOrAdmin())
						|| (this.getIsOwnerOrAdmin() != null && castOther.getIsOwnerOrAdmin() != null
								&& this.getIsOwnerOrAdmin().equals(castOther.getIsOwnerOrAdmin())))
				&& ((this.getTotalContributedProjects() == castOther.getTotalContributedProjects())
						|| (this.getTotalContributedProjects() != null
								&& castOther.getTotalContributedProjects() != null
								&& this.getTotalContributedProjects().equals(castOther.getTotalContributedProjects())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getHasAnother() == castOther.getHasAnother()) || (this.getHasAnother() != null
						&& castOther.getHasAnother() != null && this.getHasAnother().equals(castOther.getHasAnother())))
				&& ((this.getFullTextIndex() == castOther.getFullTextIndex())
						|| (this.getFullTextIndex() != null && castOther.getFullTextIndex() != null
								&& this.getFullTextIndex().equals(castOther.getFullTextIndex())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAnonymous() == null ? 0 : this.getAnonymous().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getRewardId() == null ? 0 : this.getRewardId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getProfileImgThumbnail() == null ? 0 : this.getProfileImgThumbnail().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getReward() == null ? 0 : this.getReward().hashCode());
		result = 37 * result + (getWaitingPayment() == null ? 0 : this.getWaitingPayment().hashCode());
		result = 37 * result + (getIsOwnerOrAdmin() == null ? 0 : this.getIsOwnerOrAdmin().hashCode());
		result = 37 * result
				+ (getTotalContributedProjects() == null ? 0 : this.getTotalContributedProjects().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getHasAnother() == null ? 0 : this.getHasAnother().hashCode());
		result = 37 * result + (getFullTextIndex() == null ? 0 : this.getFullTextIndex().hashCode());
		return result;
	}

}
