package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects", schema = "1")
public class Projects implements java.io.Serializable {

	private ProjectsId id;

	public Projects() {
	}

	public Projects(ProjectsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id") ),
			@AttributeOverride(name = "projectName", column = @Column(name = "project_name") ),
			@AttributeOverride(name = "headline", column = @Column(name = "headline") ),
			@AttributeOverride(name = "permalink", column = @Column(name = "permalink") ),
			@AttributeOverride(name = "mode", column = @Column(name = "mode") ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ),
			@AttributeOverride(name = "stateOrder", column = @Column(name = "state_order") ),
			@AttributeOverride(name = "onlineDate", column = @Column(name = "online_date", length = 29) ),
			@AttributeOverride(name = "recommended", column = @Column(name = "recommended") ),
			@AttributeOverride(name = "projectImg", column = @Column(name = "project_img") ),
			@AttributeOverride(name = "remainingTime", column = @Column(name = "remaining_time") ),
			@AttributeOverride(name = "expiresAt", column = @Column(name = "expires_at", length = 29) ),
			@AttributeOverride(name = "pledged", column = @Column(name = "pledged", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "progress", column = @Column(name = "progress", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "stateAcronym", column = @Column(name = "state_acronym") ),
			@AttributeOverride(name = "ownerName", column = @Column(name = "owner_name") ),
			@AttributeOverride(name = "cityName", column = @Column(name = "city_name") ),
			@AttributeOverride(name = "fullTextIndex", column = @Column(name = "full_text_index") ),
			@AttributeOverride(name = "openForContributions", column = @Column(name = "open_for_contributions") ),
			@AttributeOverride(name = "elapsedTime", column = @Column(name = "elapsed_time") ) })
	public ProjectsId getId() {
		return this.id;
	}

	public void setId(ProjectsId id) {
		this.id = id;
	}

}
