package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectAccountsId generated by hbm2java
 */
@Embeddable
public class ProjectAccountsId implements java.io.Serializable {

	private Integer id;
	private Integer projectId;
	private Integer userId;
	private String userEmail;
	private String bankName;
	private String bankCode;
	private String agency;
	private String agencyDigit;
	private String account;
	private String accountDigit;
	private String accountType;
	private String ownerName;
	private String ownerDocument;
	private String stateInscription;
	private String addressStreet;
	private String addressNumber;
	private String addressComplement;
	private String addressNeighbourhood;
	private String addressCity;
	private String addressState;
	private String addressZipCode;
	private String phoneNumber;
	private String errorReason;
	private String transferState;
	private Date transferLimitDate;

	public ProjectAccountsId() {
	}

	public ProjectAccountsId(Integer id, Integer projectId, Integer userId, String userEmail, String bankName,
			String bankCode, String agency, String agencyDigit, String account, String accountDigit, String accountType,
			String ownerName, String ownerDocument, String stateInscription, String addressStreet, String addressNumber,
			String addressComplement, String addressNeighbourhood, String addressCity, String addressState,
			String addressZipCode, String phoneNumber, String errorReason, String transferState,
			Date transferLimitDate) {
		this.id = id;
		this.projectId = projectId;
		this.userId = userId;
		this.userEmail = userEmail;
		this.bankName = bankName;
		this.bankCode = bankCode;
		this.agency = agency;
		this.agencyDigit = agencyDigit;
		this.account = account;
		this.accountDigit = accountDigit;
		this.accountType = accountType;
		this.ownerName = ownerName;
		this.ownerDocument = ownerDocument;
		this.stateInscription = stateInscription;
		this.addressStreet = addressStreet;
		this.addressNumber = addressNumber;
		this.addressComplement = addressComplement;
		this.addressNeighbourhood = addressNeighbourhood;
		this.addressCity = addressCity;
		this.addressState = addressState;
		this.addressZipCode = addressZipCode;
		this.phoneNumber = phoneNumber;
		this.errorReason = errorReason;
		this.transferState = transferState;
		this.transferLimitDate = transferLimitDate;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_email")
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "bank_name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_code")
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "agency")
	public String getAgency() {
		return this.agency;
	}

	public void setAgency(String agency) {
		this.agency = agency;
	}

	@Column(name = "agency_digit")
	public String getAgencyDigit() {
		return this.agencyDigit;
	}

	public void setAgencyDigit(String agencyDigit) {
		this.agencyDigit = agencyDigit;
	}

	@Column(name = "account")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "account_digit")
	public String getAccountDigit() {
		return this.accountDigit;
	}

	public void setAccountDigit(String accountDigit) {
		this.accountDigit = accountDigit;
	}

	@Column(name = "account_type")
	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	@Column(name = "owner_name")
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "owner_document")
	public String getOwnerDocument() {
		return this.ownerDocument;
	}

	public void setOwnerDocument(String ownerDocument) {
		this.ownerDocument = ownerDocument;
	}

	@Column(name = "state_inscription")
	public String getStateInscription() {
		return this.stateInscription;
	}

	public void setStateInscription(String stateInscription) {
		this.stateInscription = stateInscription;
	}

	@Column(name = "address_street")
	public String getAddressStreet() {
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	@Column(name = "address_number")
	public String getAddressNumber() {
		return this.addressNumber;
	}

	public void setAddressNumber(String addressNumber) {
		this.addressNumber = addressNumber;
	}

	@Column(name = "address_complement")
	public String getAddressComplement() {
		return this.addressComplement;
	}

	public void setAddressComplement(String addressComplement) {
		this.addressComplement = addressComplement;
	}

	@Column(name = "address_neighbourhood")
	public String getAddressNeighbourhood() {
		return this.addressNeighbourhood;
	}

	public void setAddressNeighbourhood(String addressNeighbourhood) {
		this.addressNeighbourhood = addressNeighbourhood;
	}

	@Column(name = "address_city")
	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	@Column(name = "address_state")
	public String getAddressState() {
		return this.addressState;
	}

	public void setAddressState(String addressState) {
		this.addressState = addressState;
	}

	@Column(name = "address_zip_code")
	public String getAddressZipCode() {
		return this.addressZipCode;
	}

	public void setAddressZipCode(String addressZipCode) {
		this.addressZipCode = addressZipCode;
	}

	@Column(name = "phone_number")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "error_reason")
	public String getErrorReason() {
		return this.errorReason;
	}

	public void setErrorReason(String errorReason) {
		this.errorReason = errorReason;
	}

	@Column(name = "transfer_state")
	public String getTransferState() {
		return this.transferState;
	}

	public void setTransferState(String transferState) {
		this.transferState = transferState;
	}

	@Column(name = "transfer_limit_date", length = 29)
	public Date getTransferLimitDate() {
		return this.transferLimitDate;
	}

	public void setTransferLimitDate(Date transferLimitDate) {
		this.transferLimitDate = transferLimitDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectAccountsId))
			return false;
		ProjectAccountsId castOther = (ProjectAccountsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this.getUserEmail() != null
						&& castOther.getUserEmail() != null && this.getUserEmail().equals(castOther.getUserEmail())))
				&& ((this.getBankName() == castOther.getBankName()) || (this.getBankName() != null
						&& castOther.getBankName() != null && this.getBankName().equals(castOther.getBankName())))
				&& ((this.getBankCode() == castOther.getBankCode()) || (this.getBankCode() != null
						&& castOther.getBankCode() != null && this.getBankCode().equals(castOther.getBankCode())))
				&& ((this.getAgency() == castOther.getAgency()) || (this.getAgency() != null
						&& castOther.getAgency() != null && this.getAgency().equals(castOther.getAgency())))
				&& ((this.getAgencyDigit() == castOther.getAgencyDigit())
						|| (this.getAgencyDigit() != null && castOther.getAgencyDigit() != null
								&& this.getAgencyDigit().equals(castOther.getAgencyDigit())))
				&& ((this.getAccount() == castOther.getAccount()) || (this.getAccount() != null
						&& castOther.getAccount() != null && this.getAccount().equals(castOther.getAccount())))
				&& ((this.getAccountDigit() == castOther.getAccountDigit())
						|| (this.getAccountDigit() != null && castOther.getAccountDigit() != null
								&& this.getAccountDigit().equals(castOther.getAccountDigit())))
				&& ((this.getAccountType() == castOther.getAccountType())
						|| (this.getAccountType() != null && castOther.getAccountType() != null
								&& this.getAccountType().equals(castOther.getAccountType())))
				&& ((this.getOwnerName() == castOther.getOwnerName()) || (this.getOwnerName() != null
						&& castOther.getOwnerName() != null && this.getOwnerName().equals(castOther.getOwnerName())))
				&& ((this.getOwnerDocument() == castOther.getOwnerDocument())
						|| (this.getOwnerDocument() != null && castOther.getOwnerDocument() != null
								&& this.getOwnerDocument().equals(castOther.getOwnerDocument())))
				&& ((this.getStateInscription() == castOther.getStateInscription())
						|| (this.getStateInscription() != null && castOther.getStateInscription() != null
								&& this.getStateInscription().equals(castOther.getStateInscription())))
				&& ((this.getAddressStreet() == castOther.getAddressStreet())
						|| (this.getAddressStreet() != null && castOther.getAddressStreet() != null
								&& this.getAddressStreet().equals(castOther.getAddressStreet())))
				&& ((this.getAddressNumber() == castOther.getAddressNumber())
						|| (this.getAddressNumber() != null && castOther.getAddressNumber() != null
								&& this.getAddressNumber().equals(castOther.getAddressNumber())))
				&& ((this.getAddressComplement() == castOther.getAddressComplement())
						|| (this.getAddressComplement() != null && castOther.getAddressComplement() != null
								&& this.getAddressComplement().equals(castOther.getAddressComplement())))
				&& ((this.getAddressNeighbourhood() == castOther.getAddressNeighbourhood())
						|| (this.getAddressNeighbourhood() != null && castOther.getAddressNeighbourhood() != null
								&& this.getAddressNeighbourhood().equals(castOther.getAddressNeighbourhood())))
				&& ((this.getAddressCity() == castOther.getAddressCity())
						|| (this.getAddressCity() != null && castOther.getAddressCity() != null
								&& this.getAddressCity().equals(castOther.getAddressCity())))
				&& ((this.getAddressState() == castOther.getAddressState())
						|| (this.getAddressState() != null && castOther.getAddressState() != null
								&& this.getAddressState().equals(castOther.getAddressState())))
				&& ((this.getAddressZipCode() == castOther.getAddressZipCode())
						|| (this.getAddressZipCode() != null && castOther.getAddressZipCode() != null
								&& this.getAddressZipCode().equals(castOther.getAddressZipCode())))
				&& ((this.getPhoneNumber() == castOther.getPhoneNumber())
						|| (this.getPhoneNumber() != null && castOther.getPhoneNumber() != null
								&& this.getPhoneNumber().equals(castOther.getPhoneNumber())))
				&& ((this.getErrorReason() == castOther.getErrorReason())
						|| (this.getErrorReason() != null && castOther.getErrorReason() != null
								&& this.getErrorReason().equals(castOther.getErrorReason())))
				&& ((this.getTransferState() == castOther.getTransferState())
						|| (this.getTransferState() != null && castOther.getTransferState() != null
								&& this.getTransferState().equals(castOther.getTransferState())))
				&& ((this.getTransferLimitDate() == castOther.getTransferLimitDate())
						|| (this.getTransferLimitDate() != null && castOther.getTransferLimitDate() != null
								&& this.getTransferLimitDate().equals(castOther.getTransferLimitDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		result = 37 * result + (getBankName() == null ? 0 : this.getBankName().hashCode());
		result = 37 * result + (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result + (getAgency() == null ? 0 : this.getAgency().hashCode());
		result = 37 * result + (getAgencyDigit() == null ? 0 : this.getAgencyDigit().hashCode());
		result = 37 * result + (getAccount() == null ? 0 : this.getAccount().hashCode());
		result = 37 * result + (getAccountDigit() == null ? 0 : this.getAccountDigit().hashCode());
		result = 37 * result + (getAccountType() == null ? 0 : this.getAccountType().hashCode());
		result = 37 * result + (getOwnerName() == null ? 0 : this.getOwnerName().hashCode());
		result = 37 * result + (getOwnerDocument() == null ? 0 : this.getOwnerDocument().hashCode());
		result = 37 * result + (getStateInscription() == null ? 0 : this.getStateInscription().hashCode());
		result = 37 * result + (getAddressStreet() == null ? 0 : this.getAddressStreet().hashCode());
		result = 37 * result + (getAddressNumber() == null ? 0 : this.getAddressNumber().hashCode());
		result = 37 * result + (getAddressComplement() == null ? 0 : this.getAddressComplement().hashCode());
		result = 37 * result + (getAddressNeighbourhood() == null ? 0 : this.getAddressNeighbourhood().hashCode());
		result = 37 * result + (getAddressCity() == null ? 0 : this.getAddressCity().hashCode());
		result = 37 * result + (getAddressState() == null ? 0 : this.getAddressState().hashCode());
		result = 37 * result + (getAddressZipCode() == null ? 0 : this.getAddressZipCode().hashCode());
		result = 37 * result + (getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode());
		result = 37 * result + (getErrorReason() == null ? 0 : this.getErrorReason().hashCode());
		result = 37 * result + (getTransferState() == null ? 0 : this.getTransferState().hashCode());
		result = 37 * result + (getTransferLimitDate() == null ? 0 : this.getTransferLimitDate().hashCode());
		return result;
	}

}
