package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectPostsDetailsId generated by hbm2java
 */
@Embeddable
public class ProjectPostsDetailsId implements java.io.Serializable {

	private Integer id;
	private Integer projectId;
	private Boolean isOwnerOrAdmin;
	private Boolean exclusive;
	private String title;
	private String commentHtml;
	private Date createdAt;

	public ProjectPostsDetailsId() {
	}

	public ProjectPostsDetailsId(Integer id, Integer projectId, Boolean isOwnerOrAdmin, Boolean exclusive, String title,
			String commentHtml, Date createdAt) {
		this.id = id;
		this.projectId = projectId;
		this.isOwnerOrAdmin = isOwnerOrAdmin;
		this.exclusive = exclusive;
		this.title = title;
		this.commentHtml = commentHtml;
		this.createdAt = createdAt;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "is_owner_or_admin")
	public Boolean getIsOwnerOrAdmin() {
		return this.isOwnerOrAdmin;
	}

	public void setIsOwnerOrAdmin(Boolean isOwnerOrAdmin) {
		this.isOwnerOrAdmin = isOwnerOrAdmin;
	}

	@Column(name = "exclusive")
	public Boolean getExclusive() {
		return this.exclusive;
	}

	public void setExclusive(Boolean exclusive) {
		this.exclusive = exclusive;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "comment_html")
	public String getCommentHtml() {
		return this.commentHtml;
	}

	public void setCommentHtml(String commentHtml) {
		this.commentHtml = commentHtml;
	}

	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectPostsDetailsId))
			return false;
		ProjectPostsDetailsId castOther = (ProjectPostsDetailsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getIsOwnerOrAdmin() == castOther.getIsOwnerOrAdmin())
						|| (this.getIsOwnerOrAdmin() != null && castOther.getIsOwnerOrAdmin() != null
								&& this.getIsOwnerOrAdmin().equals(castOther.getIsOwnerOrAdmin())))
				&& ((this.getExclusive() == castOther.getExclusive()) || (this.getExclusive() != null
						&& castOther.getExclusive() != null && this.getExclusive().equals(castOther.getExclusive())))
				&& ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
						&& castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
				&& ((this.getCommentHtml() == castOther.getCommentHtml())
						|| (this.getCommentHtml() != null && castOther.getCommentHtml() != null
								&& this.getCommentHtml().equals(castOther.getCommentHtml())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getIsOwnerOrAdmin() == null ? 0 : this.getIsOwnerOrAdmin().hashCode());
		result = 37 * result + (getExclusive() == null ? 0 : this.getExclusive().hashCode());
		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getCommentHtml() == null ? 0 : this.getCommentHtml().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		return result;
	}

}
