package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectReports generated by hbm2java
 */
@Entity
@Table(name = "project_reports", schema = "1")
public class ProjectReports implements java.io.Serializable {

	private ProjectReportsId id;

	public ProjectReports() {
	}

	public ProjectReports(ProjectReportsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "reason", column = @Column(name = "reason") ),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "email", column = @Column(name = "email") ),
			@AttributeOverride(name = "details", column = @Column(name = "details") ) })
	public ProjectReportsId getId() {
		return this.id;
	}

	public void setId(ProjectReportsId id) {
		this.id = id;
	}

}
