package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TeamMembers generated by hbm2java
 */
@Entity
@Table(name = "team_members", schema = "1")
public class TeamMembers implements java.io.Serializable {

	private TeamMembersId id;

	public TeamMembers() {
	}

	public TeamMembers(TeamMembersId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "img", column = @Column(name = "img") ),
			@AttributeOverride(name = "totalContributedProjects", column = @Column(name = "total_contributed_projects") ),
			@AttributeOverride(name = "totalAmountContributed", column = @Column(name = "total_amount_contributed", precision = 131089, scale = 0) ) })
	public TeamMembersId getId() {
		return this.id;
	}

	public void setId(TeamMembersId id) {
		this.id = id;
	}

}
