package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersId generated by hbm2java
 */
@Embeddable
public class UsersId implements java.io.Serializable {

	private Integer id;
	private String name;
	private String profileImgThumbnail;
	private String facebookLink;
	private String twitterUsername;
	private String email;
	private Date deactivatedAt;
	private Serializable fullTextIndex;

	public UsersId() {
	}

	public UsersId(Integer id, String name, String profileImgThumbnail, String facebookLink, String twitterUsername,
			String email, Date deactivatedAt, Serializable fullTextIndex) {
		this.id = id;
		this.name = name;
		this.profileImgThumbnail = profileImgThumbnail;
		this.facebookLink = facebookLink;
		this.twitterUsername = twitterUsername;
		this.email = email;
		this.deactivatedAt = deactivatedAt;
		this.fullTextIndex = fullTextIndex;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "profile_img_thumbnail")
	public String getProfileImgThumbnail() {
		return this.profileImgThumbnail;
	}

	public void setProfileImgThumbnail(String profileImgThumbnail) {
		this.profileImgThumbnail = profileImgThumbnail;
	}

	@Column(name = "facebook_link")
	public String getFacebookLink() {
		return this.facebookLink;
	}

	public void setFacebookLink(String facebookLink) {
		this.facebookLink = facebookLink;
	}

	@Column(name = "twitter_username")
	public String getTwitterUsername() {
		return this.twitterUsername;
	}

	public void setTwitterUsername(String twitterUsername) {
		this.twitterUsername = twitterUsername;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "deactivated_at", length = 29)
	public Date getDeactivatedAt() {
		return this.deactivatedAt;
	}

	public void setDeactivatedAt(Date deactivatedAt) {
		this.deactivatedAt = deactivatedAt;
	}

	@Column(name = "full_text_index")
	public Serializable getFullTextIndex() {
		return this.fullTextIndex;
	}

	public void setFullTextIndex(Serializable fullTextIndex) {
		this.fullTextIndex = fullTextIndex;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersId))
			return false;
		UsersId castOther = (UsersId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getProfileImgThumbnail() == castOther.getProfileImgThumbnail())
						|| (this.getProfileImgThumbnail() != null && castOther.getProfileImgThumbnail() != null
								&& this.getProfileImgThumbnail().equals(castOther.getProfileImgThumbnail())))
				&& ((this.getFacebookLink() == castOther.getFacebookLink())
						|| (this.getFacebookLink() != null && castOther.getFacebookLink() != null
								&& this.getFacebookLink().equals(castOther.getFacebookLink())))
				&& ((this.getTwitterUsername() == castOther.getTwitterUsername())
						|| (this.getTwitterUsername() != null && castOther.getTwitterUsername() != null
								&& this.getTwitterUsername().equals(castOther.getTwitterUsername())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getDeactivatedAt() == castOther.getDeactivatedAt())
						|| (this.getDeactivatedAt() != null && castOther.getDeactivatedAt() != null
								&& this.getDeactivatedAt().equals(castOther.getDeactivatedAt())))
				&& ((this.getFullTextIndex() == castOther.getFullTextIndex())
						|| (this.getFullTextIndex() != null && castOther.getFullTextIndex() != null
								&& this.getFullTextIndex().equals(castOther.getFullTextIndex())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getProfileImgThumbnail() == null ? 0 : this.getProfileImgThumbnail().hashCode());
		result = 37 * result + (getFacebookLink() == null ? 0 : this.getFacebookLink().hashCode());
		result = 37 * result + (getTwitterUsername() == null ? 0 : this.getTwitterUsername().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getDeactivatedAt() == null ? 0 : this.getDeactivatedAt().hashCode());
		result = 37 * result + (getFullTextIndex() == null ? 0 : this.getFullTextIndex().hashCode());
		return result;
	}

}
