package gsrc1;
// Generated 10 Jun, 2016 11:57:07 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserCredits generated by hbm2java
 */
@Entity
@Table(name = "user_credits", schema = "1")
public class UserCredits implements java.io.Serializable {

	private UserCreditsId id;

	public UserCredits() {
	}

	public UserCredits(UserCreditsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id") ),
			@AttributeOverride(name = "credits", column = @Column(name = "credits", precision = 131089, scale = 0) ) })
	public UserCreditsId getId() {
		return this.id;
	}

	public void setId(UserCreditsId id) {
		this.id = id;
	}

}
