package src3;
// Generated 13 Jun, 2016 5:44:25 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Banks generated by hbm2java
 */
@Entity
@Table(name = "banks", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "code") )
public class Banks implements java.io.Serializable {

	private int id;
	private String name;
	private String code;
	private Date createdAt;
	private Date updatedAt;
	private Set<BankAccounts> bankAccountses = new HashSet<BankAccounts>(0);
	private Set<ProjectAccounts> projectAccountses = new HashSet<ProjectAccounts>(0);

	public Banks() {
	}

	public Banks(int id, String name, String code) {
		this.id = id;
		this.name = name;
		this.code = code;
	}

	public Banks(int id, String name, String code, Date createdAt, Date updatedAt, Set<BankAccounts> bankAccountses,
			Set<ProjectAccounts> projectAccountses) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.bankAccountses = bankAccountses;
		this.projectAccountses = projectAccountses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banks")
	public Set<BankAccounts> getBankAccountses() {
		return this.bankAccountses;
	}

	public void setBankAccountses(Set<BankAccounts> bankAccountses) {
		this.bankAccountses = bankAccountses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banks")
	public Set<ProjectAccounts> getProjectAccountses() {
		return this.projectAccountses;
	}

	public void setProjectAccountses(Set<ProjectAccounts> projectAccountses) {
		this.projectAccountses = projectAccountses;
	}

}
