package src3;
// Generated 13 Jun, 2016 5:44:25 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FinancialReports generated by hbm2java
 */
@Entity
@Table(name = "financial_reports", schema = "public")
public class FinancialReports implements java.io.Serializable {

	private FinancialReportsId id;

	public FinancialReports() {
	}

	public FinancialReports(FinancialReportsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "moipLogin", column = @Column(name = "moip_login") ),
			@AttributeOverride(name = "goal", column = @Column(name = "goal", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "expiresAt", column = @Column(name = "expires_at", length = 29) ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ) })
	public FinancialReportsId getId() {
		return this.id;
	}

	public void setId(FinancialReportsId id) {
		this.id = id;
	}

}
