package src3;
// Generated 13 Jun, 2016 5:44:25 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OauthProviders generated by hbm2java
 */
@Entity
@Table(name = "oauth_providers", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class OauthProviders implements java.io.Serializable {

	private int id;
	private String name;
	private String key;
	private String secret;
	private String scope;
	private Integer order;
	private Date createdAt;
	private Date updatedAt;
	private String strategy;
	private String path;
	private Set<Authorizations> authorizationses = new HashSet<Authorizations>(0);

	public OauthProviders() {
	}

	public OauthProviders(int id, String name, String key, String secret) {
		this.id = id;
		this.name = name;
		this.key = key;
		this.secret = secret;
	}

	public OauthProviders(int id, String name, String key, String secret, String scope, Integer order, Date createdAt,
			Date updatedAt, String strategy, String path, Set<Authorizations> authorizationses) {
		this.id = id;
		this.name = name;
		this.key = key;
		this.secret = secret;
		this.scope = scope;
		this.order = order;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.strategy = strategy;
		this.path = path;
		this.authorizationses = authorizationses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "key", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "secret", nullable = false)
	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	@Column(name = "scope")
	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	@Column(name = "order")
	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "strategy")
	public String getStrategy() {
		return this.strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oauthProviders")
	public Set<Authorizations> getAuthorizationses() {
		return this.authorizationses;
	}

	public void setAuthorizationses(Set<Authorizations> authorizationses) {
		this.authorizationses = authorizationses;
	}

}
