package src3;
// Generated 13 Jun, 2016 5:44:25 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentTransfers generated by hbm2java
 */
@Entity
@Table(name = "payment_transfers", schema = "public")
public class PaymentTransfers implements java.io.Serializable {

	private int id;
	private Users users;
	private Payments payments;
	private String transferId;
	private Serializable transferData;
	private Date createdAt;
	private Date updatedAt;

	public PaymentTransfers() {
	}

	public PaymentTransfers(int id, Users users, Payments payments, String transferId) {
		this.id = id;
		this.users = users;
		this.payments = payments;
		this.transferId = transferId;
	}

	public PaymentTransfers(int id, Users users, Payments payments, String transferId, Serializable transferData,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.users = users;
		this.payments = payments;
		this.transferId = transferId;
		this.transferData = transferData;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_id", nullable = false)
	public Payments getPayments() {
		return this.payments;
	}

	public void setPayments(Payments payments) {
		this.payments = payments;
	}

	@Column(name = "transfer_id", nullable = false)
	public String getTransferId() {
		return this.transferId;
	}

	public void setTransferId(String transferId) {
		this.transferId = transferId;
	}

	@Column(name = "transfer_data")
	public Serializable getTransferData() {
		return this.transferData;
	}

	public void setTransferData(Serializable transferData) {
		this.transferData = transferData;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
