package src3;
// Generated 13 Jun, 2016 5:44:25 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaypalPaymentsId generated by hbm2java
 */
@Embeddable
public class PaypalPaymentsId implements java.io.Serializable {

	private String data;
	private String hora;
	private String fusohorario;
	private String nome;
	private String tipo;
	private String status;
	private String moeda;
	private String valorbruto;
	private String tarifa;
	private String liquido;
	private String doeMail;
	private String paraeMail;
	private String iddatransacao;
	private String statusdoequivalente;
	private String statusdoendereco;
	private String titulodoitem;
	private String iddoitem;
	private String valordoenvioemanuseio;
	private String valordoseguro;
	private String impostosobrevendas;
	private String opcao1nome;
	private String opcao1valor;
	private String opcao2nome;
	private String opcao2valor;
	private String sitedoleilao;
	private String iddocomprador;
	private String urldoitem;
	private String datadetermino;
	private String iddaescritura;
	private String iddafatura;
	private String idtxnDereferência;
	private String numerodafatura;
	private String numeropersonalizado;
	private String iddorecibo;
	private String saldo;
	private String enderecolinha1;
	private String enderecolinha2DistritoBairro;
	private String cidade;
	private String estadoRegiaoTerritórioPrefeituraRepublica;
	private String cep;
	private String pais;
	private String numerodotelefoneparacontato;
	private String extra;

	public PaypalPaymentsId() {
	}

	public PaypalPaymentsId(String data, String hora, String fusohorario, String nome, String tipo, String status,
			String moeda, String valorbruto, String tarifa, String liquido, String doeMail, String paraeMail,
			String iddatransacao, String statusdoequivalente, String statusdoendereco, String titulodoitem,
			String iddoitem, String valordoenvioemanuseio, String valordoseguro, String impostosobrevendas,
			String opcao1nome, String opcao1valor, String opcao2nome, String opcao2valor, String sitedoleilao,
			String iddocomprador, String urldoitem, String datadetermino, String iddaescritura, String iddafatura,
			String idtxnDereferência, String numerodafatura, String numeropersonalizado, String iddorecibo,
			String saldo, String enderecolinha1, String enderecolinha2DistritoBairro, String cidade,
			String estadoRegiaoTerritórioPrefeituraRepublica, String cep, String pais,
			String numerodotelefoneparacontato, String extra) {
		this.data = data;
		this.hora = hora;
		this.fusohorario = fusohorario;
		this.nome = nome;
		this.tipo = tipo;
		this.status = status;
		this.moeda = moeda;
		this.valorbruto = valorbruto;
		this.tarifa = tarifa;
		this.liquido = liquido;
		this.doeMail = doeMail;
		this.paraeMail = paraeMail;
		this.iddatransacao = iddatransacao;
		this.statusdoequivalente = statusdoequivalente;
		this.statusdoendereco = statusdoendereco;
		this.titulodoitem = titulodoitem;
		this.iddoitem = iddoitem;
		this.valordoenvioemanuseio = valordoenvioemanuseio;
		this.valordoseguro = valordoseguro;
		this.impostosobrevendas = impostosobrevendas;
		this.opcao1nome = opcao1nome;
		this.opcao1valor = opcao1valor;
		this.opcao2nome = opcao2nome;
		this.opcao2valor = opcao2valor;
		this.sitedoleilao = sitedoleilao;
		this.iddocomprador = iddocomprador;
		this.urldoitem = urldoitem;
		this.datadetermino = datadetermino;
		this.iddaescritura = iddaescritura;
		this.iddafatura = iddafatura;
		this.idtxnDereferência = idtxnDereferência;
		this.numerodafatura = numerodafatura;
		this.numeropersonalizado = numeropersonalizado;
		this.iddorecibo = iddorecibo;
		this.saldo = saldo;
		this.enderecolinha1 = enderecolinha1;
		this.enderecolinha2DistritoBairro = enderecolinha2DistritoBairro;
		this.cidade = cidade;
		this.estadoRegiaoTerritórioPrefeituraRepublica = estadoRegiaoTerritórioPrefeituraRepublica;
		this.cep = cep;
		this.pais = pais;
		this.numerodotelefoneparacontato = numerodotelefoneparacontato;
		this.extra = extra;
	}

	@Column(name = "data")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "hora")
	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	@Column(name = "fusohorario")
	public String getFusohorario() {
		return this.fusohorario;
	}

	public void setFusohorario(String fusohorario) {
		this.fusohorario = fusohorario;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "moeda")
	public String getMoeda() {
		return this.moeda;
	}

	public void setMoeda(String moeda) {
		this.moeda = moeda;
	}

	@Column(name = "valorbruto")
	public String getValorbruto() {
		return this.valorbruto;
	}

	public void setValorbruto(String valorbruto) {
		this.valorbruto = valorbruto;
	}

	@Column(name = "tarifa")
	public String getTarifa() {
		return this.tarifa;
	}

	public void setTarifa(String tarifa) {
		this.tarifa = tarifa;
	}

	@Column(name = "liquido")
	public String getLiquido() {
		return this.liquido;
	}

	public void setLiquido(String liquido) {
		this.liquido = liquido;
	}

	@Column(name = "doe_mail")
	public String getDoeMail() {
		return this.doeMail;
	}

	public void setDoeMail(String doeMail) {
		this.doeMail = doeMail;
	}

	@Column(name = "parae_mail")
	public String getParaeMail() {
		return this.paraeMail;
	}

	public void setParaeMail(String paraeMail) {
		this.paraeMail = paraeMail;
	}

	@Column(name = "iddatransacao")
	public String getIddatransacao() {
		return this.iddatransacao;
	}

	public void setIddatransacao(String iddatransacao) {
		this.iddatransacao = iddatransacao;
	}

	@Column(name = "statusdoequivalente")
	public String getStatusdoequivalente() {
		return this.statusdoequivalente;
	}

	public void setStatusdoequivalente(String statusdoequivalente) {
		this.statusdoequivalente = statusdoequivalente;
	}

	@Column(name = "statusdoendereco")
	public String getStatusdoendereco() {
		return this.statusdoendereco;
	}

	public void setStatusdoendereco(String statusdoendereco) {
		this.statusdoendereco = statusdoendereco;
	}

	@Column(name = "titulodoitem")
	public String getTitulodoitem() {
		return this.titulodoitem;
	}

	public void setTitulodoitem(String titulodoitem) {
		this.titulodoitem = titulodoitem;
	}

	@Column(name = "iddoitem")
	public String getIddoitem() {
		return this.iddoitem;
	}

	public void setIddoitem(String iddoitem) {
		this.iddoitem = iddoitem;
	}

	@Column(name = "valordoenvioemanuseio")
	public String getValordoenvioemanuseio() {
		return this.valordoenvioemanuseio;
	}

	public void setValordoenvioemanuseio(String valordoenvioemanuseio) {
		this.valordoenvioemanuseio = valordoenvioemanuseio;
	}

	@Column(name = "valordoseguro")
	public String getValordoseguro() {
		return this.valordoseguro;
	}

	public void setValordoseguro(String valordoseguro) {
		this.valordoseguro = valordoseguro;
	}

	@Column(name = "impostosobrevendas")
	public String getImpostosobrevendas() {
		return this.impostosobrevendas;
	}

	public void setImpostosobrevendas(String impostosobrevendas) {
		this.impostosobrevendas = impostosobrevendas;
	}

	@Column(name = "opcao1nome")
	public String getOpcao1nome() {
		return this.opcao1nome;
	}

	public void setOpcao1nome(String opcao1nome) {
		this.opcao1nome = opcao1nome;
	}

	@Column(name = "opcao1valor")
	public String getOpcao1valor() {
		return this.opcao1valor;
	}

	public void setOpcao1valor(String opcao1valor) {
		this.opcao1valor = opcao1valor;
	}

	@Column(name = "opcao2nome")
	public String getOpcao2nome() {
		return this.opcao2nome;
	}

	public void setOpcao2nome(String opcao2nome) {
		this.opcao2nome = opcao2nome;
	}

	@Column(name = "opcao2valor")
	public String getOpcao2valor() {
		return this.opcao2valor;
	}

	public void setOpcao2valor(String opcao2valor) {
		this.opcao2valor = opcao2valor;
	}

	@Column(name = "sitedoleilao")
	public String getSitedoleilao() {
		return this.sitedoleilao;
	}

	public void setSitedoleilao(String sitedoleilao) {
		this.sitedoleilao = sitedoleilao;
	}

	@Column(name = "iddocomprador")
	public String getIddocomprador() {
		return this.iddocomprador;
	}

	public void setIddocomprador(String iddocomprador) {
		this.iddocomprador = iddocomprador;
	}

	@Column(name = "urldoitem")
	public String getUrldoitem() {
		return this.urldoitem;
	}

	public void setUrldoitem(String urldoitem) {
		this.urldoitem = urldoitem;
	}

	@Column(name = "datadetermino")
	public String getDatadetermino() {
		return this.datadetermino;
	}

	public void setDatadetermino(String datadetermino) {
		this.datadetermino = datadetermino;
	}

	@Column(name = "iddaescritura")
	public String getIddaescritura() {
		return this.iddaescritura;
	}

	public void setIddaescritura(String iddaescritura) {
		this.iddaescritura = iddaescritura;
	}

	@Column(name = "iddafatura")
	public String getIddafatura() {
		return this.iddafatura;
	}

	public void setIddafatura(String iddafatura) {
		this.iddafatura = iddafatura;
	}

	@Column(name = "idtxn_dereferência")
	public String getIdtxnDereferência() {
		return this.idtxnDereferência;
	}

	public void setIdtxnDereferência(String idtxnDereferência) {
		this.idtxnDereferência = idtxnDereferência;
	}

	@Column(name = "numerodafatura")
	public String getNumerodafatura() {
		return this.numerodafatura;
	}

	public void setNumerodafatura(String numerodafatura) {
		this.numerodafatura = numerodafatura;
	}

	@Column(name = "numeropersonalizado")
	public String getNumeropersonalizado() {
		return this.numeropersonalizado;
	}

	public void setNumeropersonalizado(String numeropersonalizado) {
		this.numeropersonalizado = numeropersonalizado;
	}

	@Column(name = "iddorecibo")
	public String getIddorecibo() {
		return this.iddorecibo;
	}

	public void setIddorecibo(String iddorecibo) {
		this.iddorecibo = iddorecibo;
	}

	@Column(name = "saldo")
	public String getSaldo() {
		return this.saldo;
	}

	public void setSaldo(String saldo) {
		this.saldo = saldo;
	}

	@Column(name = "enderecolinha1")
	public String getEnderecolinha1() {
		return this.enderecolinha1;
	}

	public void setEnderecolinha1(String enderecolinha1) {
		this.enderecolinha1 = enderecolinha1;
	}

	@Column(name = "enderecolinha2_distrito_bairro")
	public String getEnderecolinha2DistritoBairro() {
		return this.enderecolinha2DistritoBairro;
	}

	public void setEnderecolinha2DistritoBairro(String enderecolinha2DistritoBairro) {
		this.enderecolinha2DistritoBairro = enderecolinha2DistritoBairro;
	}

	@Column(name = "cidade")
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "estado_regiao_território_prefeitura_republica")
	public String getEstadoRegiaoTerritórioPrefeituraRepublica() {
		return this.estadoRegiaoTerritórioPrefeituraRepublica;
	}

	public void setEstadoRegiaoTerritórioPrefeituraRepublica(String estadoRegiaoTerritórioPrefeituraRepublica) {
		this.estadoRegiaoTerritórioPrefeituraRepublica = estadoRegiaoTerritórioPrefeituraRepublica;
	}

	@Column(name = "cep")
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "pais")
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "numerodotelefoneparacontato")
	public String getNumerodotelefoneparacontato() {
		return this.numerodotelefoneparacontato;
	}

	public void setNumerodotelefoneparacontato(String numerodotelefoneparacontato) {
		this.numerodotelefoneparacontato = numerodotelefoneparacontato;
	}

	@Column(name = "extra")
	public String getExtra() {
		return this.extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaypalPaymentsId))
			return false;
		PaypalPaymentsId castOther = (PaypalPaymentsId) other;

		return ((this.getData() == castOther.getData()) || (this.getData() != null && castOther.getData() != null
				&& this.getData().equals(castOther.getData())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null && castOther.getHora() != null
						&& this.getHora().equals(castOther.getHora())))
				&& ((this.getFusohorario() == castOther.getFusohorario())
						|| (this.getFusohorario() != null && castOther.getFusohorario() != null
								&& this.getFusohorario().equals(castOther.getFusohorario())))
				&& ((this.getNome() == castOther.getNome()) || (this.getNome() != null && castOther.getNome() != null
						&& this.getNome().equals(castOther.getNome())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getMoeda() == castOther.getMoeda()) || (this.getMoeda() != null
						&& castOther.getMoeda() != null && this.getMoeda().equals(castOther.getMoeda())))
				&& ((this.getValorbruto() == castOther.getValorbruto()) || (this.getValorbruto() != null
						&& castOther.getValorbruto() != null && this.getValorbruto().equals(castOther.getValorbruto())))
				&& ((this.getTarifa() == castOther.getTarifa()) || (this.getTarifa() != null
						&& castOther.getTarifa() != null && this.getTarifa().equals(castOther.getTarifa())))
				&& ((this.getLiquido() == castOther.getLiquido()) || (this.getLiquido() != null
						&& castOther.getLiquido() != null && this.getLiquido().equals(castOther.getLiquido())))
				&& ((this.getDoeMail() == castOther.getDoeMail()) || (this.getDoeMail() != null
						&& castOther.getDoeMail() != null && this.getDoeMail().equals(castOther.getDoeMail())))
				&& ((this.getParaeMail() == castOther.getParaeMail()) || (this.getParaeMail() != null
						&& castOther.getParaeMail() != null && this.getParaeMail().equals(castOther.getParaeMail())))
				&& ((this.getIddatransacao() == castOther.getIddatransacao())
						|| (this.getIddatransacao() != null && castOther.getIddatransacao() != null
								&& this.getIddatransacao().equals(castOther.getIddatransacao())))
				&& ((this.getStatusdoequivalente() == castOther.getStatusdoequivalente())
						|| (this.getStatusdoequivalente() != null && castOther.getStatusdoequivalente() != null
								&& this.getStatusdoequivalente().equals(castOther.getStatusdoequivalente())))
				&& ((this.getStatusdoendereco() == castOther.getStatusdoendereco())
						|| (this.getStatusdoendereco() != null && castOther.getStatusdoendereco() != null
								&& this.getStatusdoendereco().equals(castOther.getStatusdoendereco())))
				&& ((this.getTitulodoitem() == castOther.getTitulodoitem())
						|| (this.getTitulodoitem() != null && castOther.getTitulodoitem() != null
								&& this.getTitulodoitem().equals(castOther.getTitulodoitem())))
				&& ((this.getIddoitem() == castOther.getIddoitem()) || (this.getIddoitem() != null
						&& castOther.getIddoitem() != null && this.getIddoitem().equals(castOther.getIddoitem())))
				&& ((this.getValordoenvioemanuseio() == castOther.getValordoenvioemanuseio())
						|| (this.getValordoenvioemanuseio() != null && castOther.getValordoenvioemanuseio() != null
								&& this.getValordoenvioemanuseio().equals(castOther.getValordoenvioemanuseio())))
				&& ((this.getValordoseguro() == castOther.getValordoseguro())
						|| (this.getValordoseguro() != null && castOther.getValordoseguro() != null
								&& this.getValordoseguro().equals(castOther.getValordoseguro())))
				&& ((this.getImpostosobrevendas() == castOther.getImpostosobrevendas())
						|| (this.getImpostosobrevendas() != null && castOther.getImpostosobrevendas() != null
								&& this.getImpostosobrevendas().equals(castOther.getImpostosobrevendas())))
				&& ((this.getOpcao1nome() == castOther.getOpcao1nome()) || (this.getOpcao1nome() != null
						&& castOther.getOpcao1nome() != null && this.getOpcao1nome().equals(castOther.getOpcao1nome())))
				&& ((this.getOpcao1valor() == castOther.getOpcao1valor())
						|| (this.getOpcao1valor() != null && castOther.getOpcao1valor() != null
								&& this.getOpcao1valor().equals(castOther.getOpcao1valor())))
				&& ((this.getOpcao2nome() == castOther.getOpcao2nome()) || (this.getOpcao2nome() != null
						&& castOther.getOpcao2nome() != null && this.getOpcao2nome().equals(castOther.getOpcao2nome())))
				&& ((this.getOpcao2valor() == castOther.getOpcao2valor())
						|| (this.getOpcao2valor() != null && castOther.getOpcao2valor() != null
								&& this.getOpcao2valor().equals(castOther.getOpcao2valor())))
				&& ((this.getSitedoleilao() == castOther.getSitedoleilao())
						|| (this.getSitedoleilao() != null && castOther.getSitedoleilao() != null
								&& this.getSitedoleilao().equals(castOther.getSitedoleilao())))
				&& ((this.getIddocomprador() == castOther.getIddocomprador())
						|| (this.getIddocomprador() != null && castOther.getIddocomprador() != null
								&& this.getIddocomprador().equals(castOther.getIddocomprador())))
				&& ((this.getUrldoitem() == castOther.getUrldoitem()) || (this.getUrldoitem() != null
						&& castOther.getUrldoitem() != null && this.getUrldoitem().equals(castOther.getUrldoitem())))
				&& ((this.getDatadetermino() == castOther.getDatadetermino())
						|| (this.getDatadetermino() != null && castOther.getDatadetermino() != null
								&& this.getDatadetermino().equals(castOther.getDatadetermino())))
				&& ((this.getIddaescritura() == castOther.getIddaescritura())
						|| (this.getIddaescritura() != null && castOther.getIddaescritura() != null
								&& this.getIddaescritura().equals(castOther.getIddaescritura())))
				&& ((this.getIddafatura() == castOther.getIddafatura()) || (this.getIddafatura() != null
						&& castOther.getIddafatura() != null && this.getIddafatura().equals(castOther.getIddafatura())))
				&& ((this.getIdtxnDereferência() == castOther.getIdtxnDereferência())
						|| (this.getIdtxnDereferência() != null && castOther.getIdtxnDereferência() != null
								&& this.getIdtxnDereferência().equals(castOther.getIdtxnDereferência())))
				&& ((this.getNumerodafatura() == castOther.getNumerodafatura())
						|| (this.getNumerodafatura() != null && castOther.getNumerodafatura() != null
								&& this.getNumerodafatura().equals(castOther.getNumerodafatura())))
				&& ((this.getNumeropersonalizado() == castOther.getNumeropersonalizado())
						|| (this.getNumeropersonalizado() != null && castOther.getNumeropersonalizado() != null
								&& this.getNumeropersonalizado().equals(castOther.getNumeropersonalizado())))
				&& ((this.getIddorecibo() == castOther.getIddorecibo()) || (this.getIddorecibo() != null
						&& castOther.getIddorecibo() != null && this.getIddorecibo().equals(castOther.getIddorecibo())))
				&& ((this.getSaldo() == castOther.getSaldo()) || (this.getSaldo() != null
						&& castOther.getSaldo() != null && this.getSaldo().equals(castOther.getSaldo())))
				&& ((this.getEnderecolinha1() == castOther.getEnderecolinha1())
						|| (this.getEnderecolinha1() != null && castOther.getEnderecolinha1() != null
								&& this.getEnderecolinha1().equals(castOther.getEnderecolinha1())))
				&& ((this.getEnderecolinha2DistritoBairro() == castOther.getEnderecolinha2DistritoBairro())
						|| (this.getEnderecolinha2DistritoBairro() != null
								&& castOther.getEnderecolinha2DistritoBairro() != null
								&& this.getEnderecolinha2DistritoBairro()
										.equals(castOther.getEnderecolinha2DistritoBairro())))
				&& ((this.getCidade() == castOther.getCidade()) || (this.getCidade() != null
						&& castOther.getCidade() != null && this.getCidade().equals(castOther.getCidade())))
				&& ((this.getEstadoRegiaoTerritórioPrefeituraRepublica() == castOther
						.getEstadoRegiaoTerritórioPrefeituraRepublica())
						|| (this.getEstadoRegiaoTerritórioPrefeituraRepublica() != null
								&& castOther.getEstadoRegiaoTerritórioPrefeituraRepublica() != null
								&& this.getEstadoRegiaoTerritórioPrefeituraRepublica()
										.equals(castOther.getEstadoRegiaoTerritórioPrefeituraRepublica())))
				&& ((this.getCep() == castOther.getCep()) || (this.getCep() != null && castOther.getCep() != null
						&& this.getCep().equals(castOther.getCep())))
				&& ((this.getPais() == castOther.getPais()) || (this.getPais() != null && castOther.getPais() != null
						&& this.getPais().equals(castOther.getPais())))
				&& ((this.getNumerodotelefoneparacontato() == castOther.getNumerodotelefoneparacontato())
						|| (this.getNumerodotelefoneparacontato() != null
								&& castOther.getNumerodotelefoneparacontato() != null
								&& this.getNumerodotelefoneparacontato()
										.equals(castOther.getNumerodotelefoneparacontato())))
				&& ((this.getExtra() == castOther.getExtra()) || (this.getExtra() != null
						&& castOther.getExtra() != null && this.getExtra().equals(castOther.getExtra())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getData() == null ? 0 : this.getData().hashCode());
		result = 37 * result + (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result + (getFusohorario() == null ? 0 : this.getFusohorario().hashCode());
		result = 37 * result + (getNome() == null ? 0 : this.getNome().hashCode());
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getMoeda() == null ? 0 : this.getMoeda().hashCode());
		result = 37 * result + (getValorbruto() == null ? 0 : this.getValorbruto().hashCode());
		result = 37 * result + (getTarifa() == null ? 0 : this.getTarifa().hashCode());
		result = 37 * result + (getLiquido() == null ? 0 : this.getLiquido().hashCode());
		result = 37 * result + (getDoeMail() == null ? 0 : this.getDoeMail().hashCode());
		result = 37 * result + (getParaeMail() == null ? 0 : this.getParaeMail().hashCode());
		result = 37 * result + (getIddatransacao() == null ? 0 : this.getIddatransacao().hashCode());
		result = 37 * result + (getStatusdoequivalente() == null ? 0 : this.getStatusdoequivalente().hashCode());
		result = 37 * result + (getStatusdoendereco() == null ? 0 : this.getStatusdoendereco().hashCode());
		result = 37 * result + (getTitulodoitem() == null ? 0 : this.getTitulodoitem().hashCode());
		result = 37 * result + (getIddoitem() == null ? 0 : this.getIddoitem().hashCode());
		result = 37 * result + (getValordoenvioemanuseio() == null ? 0 : this.getValordoenvioemanuseio().hashCode());
		result = 37 * result + (getValordoseguro() == null ? 0 : this.getValordoseguro().hashCode());
		result = 37 * result + (getImpostosobrevendas() == null ? 0 : this.getImpostosobrevendas().hashCode());
		result = 37 * result + (getOpcao1nome() == null ? 0 : this.getOpcao1nome().hashCode());
		result = 37 * result + (getOpcao1valor() == null ? 0 : this.getOpcao1valor().hashCode());
		result = 37 * result + (getOpcao2nome() == null ? 0 : this.getOpcao2nome().hashCode());
		result = 37 * result + (getOpcao2valor() == null ? 0 : this.getOpcao2valor().hashCode());
		result = 37 * result + (getSitedoleilao() == null ? 0 : this.getSitedoleilao().hashCode());
		result = 37 * result + (getIddocomprador() == null ? 0 : this.getIddocomprador().hashCode());
		result = 37 * result + (getUrldoitem() == null ? 0 : this.getUrldoitem().hashCode());
		result = 37 * result + (getDatadetermino() == null ? 0 : this.getDatadetermino().hashCode());
		result = 37 * result + (getIddaescritura() == null ? 0 : this.getIddaescritura().hashCode());
		result = 37 * result + (getIddafatura() == null ? 0 : this.getIddafatura().hashCode());
		result = 37 * result + (getIdtxnDereferência() == null ? 0 : this.getIdtxnDereferência().hashCode());
		result = 37 * result + (getNumerodafatura() == null ? 0 : this.getNumerodafatura().hashCode());
		result = 37 * result + (getNumeropersonalizado() == null ? 0 : this.getNumeropersonalizado().hashCode());
		result = 37 * result + (getIddorecibo() == null ? 0 : this.getIddorecibo().hashCode());
		result = 37 * result + (getSaldo() == null ? 0 : this.getSaldo().hashCode());
		result = 37 * result + (getEnderecolinha1() == null ? 0 : this.getEnderecolinha1().hashCode());
		result = 37 * result
				+ (getEnderecolinha2DistritoBairro() == null ? 0 : this.getEnderecolinha2DistritoBairro().hashCode());
		result = 37 * result + (getCidade() == null ? 0 : this.getCidade().hashCode());
		result = 37 * result + (getEstadoRegiaoTerritórioPrefeituraRepublica() == null ? 0
				: this.getEstadoRegiaoTerritórioPrefeituraRepublica().hashCode());
		result = 37 * result + (getCep() == null ? 0 : this.getCep().hashCode());
		result = 37 * result + (getPais() == null ? 0 : this.getPais().hashCode());
		result = 37 * result
				+ (getNumerodotelefoneparacontato() == null ? 0 : this.getNumerodotelefoneparacontato().hashCode());
		result = 37 * result + (getExtra() == null ? 0 : this.getExtra().hashCode());
		return result;
	}

}
