package src3;
// Generated 13 Jun, 2016 5:44:25 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SubscriberReports generated by hbm2java
 */
@Entity
@Table(name = "subscriber_reports", schema = "public")
public class SubscriberReports implements java.io.Serializable {

	private SubscriberReportsId id;

	public SubscriberReports() {
	}

	public SubscriberReports(SubscriberReportsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id") ),
			@AttributeOverride(name = "channelId", column = @Column(name = "channel_id") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "email", column = @Column(name = "email") ) })
	public SubscriberReportsId getId() {
		return this.id;
	}

	public void setId(SubscriberReportsId id) {
		this.id = id;
	}

}
