package src3;
// Generated 13 Jun, 2016 5:44:25 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "slug") )
public class Tags implements java.io.Serializable {

	private int id;
	private String name;
	private String slug;
	private Date createdAt;
	private Date updatedAt;
	private Set<Taggings> taggingses = new HashSet<Taggings>(0);

	public Tags() {
	}

	public Tags(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Tags(int id, String name, String slug, Date createdAt, Date updatedAt, Set<Taggings> taggingses) {
		this.id = id;
		this.name = name;
		this.slug = slug;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.taggingses = taggingses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", unique = true)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set<Taggings> getTaggingses() {
		return this.taggingses;
	}

	public void setTaggingses(Set<Taggings> taggingses) {
		this.taggingses = taggingses;
	}

}
