package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * BankAccounts generated by hbm2java
 */
public class BankAccounts implements java.io.Serializable {

	private int id;
	private Users users;
	private Banks banks;
	private String account;
	private String agency;
	private String ownerName;
	private String ownerDocument;
	private Date createdAt;
	private Date updatedAt;
	private String accountDigit;
	private String agencyDigit;

	public BankAccounts() {
	}

	public BankAccounts(int id, Banks banks, String account, String agency, String ownerName, String ownerDocument,
			String accountDigit) {
		this.id = id;
		this.banks = banks;
		this.account = account;
		this.agency = agency;
		this.ownerName = ownerName;
		this.ownerDocument = ownerDocument;
		this.accountDigit = accountDigit;
	}

	public BankAccounts(int id, Users users, Banks banks, String account, String agency, String ownerName,
			String ownerDocument, Date createdAt, Date updatedAt, String accountDigit, String agencyDigit) {
		this.id = id;
		this.users = users;
		this.banks = banks;
		this.account = account;
		this.agency = agency;
		this.ownerName = ownerName;
		this.ownerDocument = ownerDocument;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.accountDigit = accountDigit;
		this.agencyDigit = agencyDigit;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Banks getBanks() {
		return this.banks;
	}

	public void setBanks(Banks banks) {
		this.banks = banks;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAgency() {
		return this.agency;
	}

	public void setAgency(String agency) {
		this.agency = agency;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public String getOwnerDocument() {
		return this.ownerDocument;
	}

	public void setOwnerDocument(String ownerDocument) {
		this.ownerDocument = ownerDocument;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getAccountDigit() {
		return this.accountDigit;
	}

	public void setAccountDigit(String accountDigit) {
		this.accountDigit = accountDigit;
	}

	public String getAgencyDigit() {
		return this.agencyDigit;
	}

	public void setAgencyDigit(String agencyDigit) {
		this.agencyDigit = agencyDigit;
	}

}
