package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Banks generated by hbm2java
 */
public class Banks implements java.io.Serializable {

	private int id;
	private String name;
	private String code;
	private Date createdAt;
	private Date updatedAt;
	private Set<BankAccounts> bankAccountses = new HashSet<BankAccounts>(0);
	private Set<ProjectAccounts> projectAccountses = new HashSet<ProjectAccounts>(0);

	public Banks() {
	}

	public Banks(int id, String name, String code) {
		this.id = id;
		this.name = name;
		this.code = code;
	}

	public Banks(int id, String name, String code, Date createdAt, Date updatedAt, Set<BankAccounts> bankAccountses,
			Set<ProjectAccounts> projectAccountses) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.bankAccountses = bankAccountses;
		this.projectAccountses = projectAccountses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<BankAccounts> getBankAccountses() {
		return this.bankAccountses;
	}

	public void setBankAccountses(Set<BankAccounts> bankAccountses) {
		this.bankAccountses = bankAccountses;
	}

	public Set<ProjectAccounts> getProjectAccountses() {
		return this.projectAccountses;
	}

	public void setProjectAccountses(Set<ProjectAccounts> projectAccountses) {
		this.projectAccountses = projectAccountses;
	}

}
