package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * ChannelPartners generated by hbm2java
 */
public class ChannelPartners implements java.io.Serializable {

	private int id;
	private Channels channels;
	private String url;
	private String image;
	private Date createdAt;
	private Date updatedAt;

	public ChannelPartners() {
	}

	public ChannelPartners(int id, Channels channels, String url, String image) {
		this.id = id;
		this.channels = channels;
		this.url = url;
		this.image = image;
	}

	public ChannelPartners(int id, Channels channels, String url, String image, Date createdAt, Date updatedAt) {
		this.id = id;
		this.channels = channels;
		this.url = url;
		this.image = image;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Channels getChannels() {
		return this.channels;
	}

	public void setChannels(Channels channels) {
		this.channels = channels;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
