package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * CreditCards generated by hbm2java
 */
public class CreditCards implements java.io.Serializable {

	private int id;
	private Users users;
	private String lastDigits;
	private String cardBrand;
	private String subscriptionId;
	private Date createdAt;
	private Date updatedAt;
	private String cardKey;

	public CreditCards() {
	}

	public CreditCards(int id, String lastDigits, String cardBrand) {
		this.id = id;
		this.lastDigits = lastDigits;
		this.cardBrand = cardBrand;
	}

	public CreditCards(int id, Users users, String lastDigits, String cardBrand, String subscriptionId, Date createdAt,
			Date updatedAt, String cardKey) {
		this.id = id;
		this.users = users;
		this.lastDigits = lastDigits;
		this.cardBrand = cardBrand;
		this.subscriptionId = subscriptionId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.cardKey = cardKey;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getLastDigits() {
		return this.lastDigits;
	}

	public void setLastDigits(String lastDigits) {
		this.lastDigits = lastDigits;
	}

	public String getCardBrand() {
		return this.cardBrand;
	}

	public void setCardBrand(String cardBrand) {
		this.cardBrand = cardBrand;
	}

	public String getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(String subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getCardKey() {
		return this.cardKey;
	}

	public void setCardKey(String cardKey) {
		this.cardKey = cardKey;
	}

}
