package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

/**
 * DepsSavedDdl generated by hbm2java
 */
public class DepsSavedDdl implements java.io.Serializable {

	private int depsId;
	private String depsViewSchema;
	private String depsViewName;
	private String depsDdlToRun;

	public DepsSavedDdl() {
	}

	public DepsSavedDdl(int depsId) {
		this.depsId = depsId;
	}

	public DepsSavedDdl(int depsId, String depsViewSchema, String depsViewName, String depsDdlToRun) {
		this.depsId = depsId;
		this.depsViewSchema = depsViewSchema;
		this.depsViewName = depsViewName;
		this.depsDdlToRun = depsDdlToRun;
	}

	public int getDepsId() {
		return this.depsId;
	}

	public void setDepsId(int depsId) {
		this.depsId = depsId;
	}

	public String getDepsViewSchema() {
		return this.depsViewSchema;
	}

	public void setDepsViewSchema(String depsViewSchema) {
		this.depsViewSchema = depsViewSchema;
	}

	public String getDepsViewName() {
		return this.depsViewName;
	}

	public void setDepsViewName(String depsViewName) {
		this.depsViewName = depsViewName;
	}

	public String getDepsDdlToRun() {
		return this.depsDdlToRun;
	}

	public void setDepsDdlToRun(String depsDdlToRun) {
		this.depsDdlToRun = depsDdlToRun;
	}

}
