package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donations generated by hbm2java
 */
public class Donations implements java.io.Serializable {

	private int id;
	private Users users;
	private Date createdAt;
	private Date updatedAt;
	private Integer amount;
	private Set<Contributions> contributionses = new HashSet<Contributions>(0);
	private Set<DonationNotifications> donationNotificationses = new HashSet<DonationNotifications>(0);

	public Donations() {
	}

	public Donations(int id) {
		this.id = id;
	}

	public Donations(int id, Users users, Date createdAt, Date updatedAt, Integer amount,
			Set<Contributions> contributionses, Set<DonationNotifications> donationNotificationses) {
		this.id = id;
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.amount = amount;
		this.contributionses = contributionses;
		this.donationNotificationses = donationNotificationses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Set<Contributions> getContributionses() {
		return this.contributionses;
	}

	public void setContributionses(Set<Contributions> contributionses) {
		this.contributionses = contributionses;
	}

	public Set<DonationNotifications> getDonationNotificationses() {
		return this.donationNotificationses;
	}

	public void setDonationNotificationses(Set<DonationNotifications> donationNotificationses) {
		this.donationNotificationses = donationNotificationses;
	}

}
