package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FlexibleProjects generated by hbm2java
 */
public class FlexibleProjects implements java.io.Serializable {

	private int id;
	private FlexibleProjectStates flexibleProjectStates;
	private Projects projects;
	private Date createdAt;
	private Date updatedAt;
	private Set<FlexibleProjectTransitions> flexibleProjectTransitionses = new HashSet<FlexibleProjectTransitions>(0);

	public FlexibleProjects() {
	}

	public FlexibleProjects(int id, FlexibleProjectStates flexibleProjectStates, Projects projects) {
		this.id = id;
		this.flexibleProjectStates = flexibleProjectStates;
		this.projects = projects;
	}

	public FlexibleProjects(int id, FlexibleProjectStates flexibleProjectStates, Projects projects, Date createdAt,
			Date updatedAt, Set<FlexibleProjectTransitions> flexibleProjectTransitionses) {
		this.id = id;
		this.flexibleProjectStates = flexibleProjectStates;
		this.projects = projects;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.flexibleProjectTransitionses = flexibleProjectTransitionses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public FlexibleProjectStates getFlexibleProjectStates() {
		return this.flexibleProjectStates;
	}

	public void setFlexibleProjectStates(FlexibleProjectStates flexibleProjectStates) {
		this.flexibleProjectStates = flexibleProjectStates;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<FlexibleProjectTransitions> getFlexibleProjectTransitionses() {
		return this.flexibleProjectTransitionses;
	}

	public void setFlexibleProjectTransitionses(Set<FlexibleProjectTransitions> flexibleProjectTransitionses) {
		this.flexibleProjectTransitionses = flexibleProjectTransitionses;
	}

}
