package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

/**
 * NearMes generated by hbm2java
 */
public class NearMes implements java.io.Serializable {

	private int id;

	public NearMes() {
	}

	public NearMes(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
