package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Origins generated by hbm2java
 */
public class Origins implements java.io.Serializable {

	private int id;
	private String domain;
	private String referral;
	private Date createdAt;
	private Date updatedAt;
	private Set<Contributions> contributionses = new HashSet<Contributions>(0);
	private Set<Projects> projectses = new HashSet<Projects>(0);

	public Origins() {
	}

	public Origins(int id, String domain) {
		this.id = id;
		this.domain = domain;
	}

	public Origins(int id, String domain, String referral, Date createdAt, Date updatedAt,
			Set<Contributions> contributionses, Set<Projects> projectses) {
		this.id = id;
		this.domain = domain;
		this.referral = referral;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.contributionses = contributionses;
		this.projectses = projectses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getReferral() {
		return this.referral;
	}

	public void setReferral(String referral) {
		this.referral = referral;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Contributions> getContributionses() {
		return this.contributionses;
	}

	public void setContributionses(Set<Contributions> contributionses) {
		this.contributionses = contributionses;
	}

	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

}
