package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * PaymentNotifications generated by hbm2java
 */
public class PaymentNotifications implements java.io.Serializable {

	private int id;
	private Contributions contributions;
	private Payments payments;
	private String extraData;
	private Date createdAt;
	private Date updatedAt;

	public PaymentNotifications() {
	}

	public PaymentNotifications(int id, Contributions contributions, Date createdAt, Date updatedAt) {
		this.id = id;
		this.contributions = contributions;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public PaymentNotifications(int id, Contributions contributions, Payments payments, String extraData,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.contributions = contributions;
		this.payments = payments;
		this.extraData = extraData;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Contributions getContributions() {
		return this.contributions;
	}

	public void setContributions(Contributions contributions) {
		this.contributions = contributions;
	}

	public Payments getPayments() {
		return this.payments;
	}

	public void setPayments(Payments payments) {
		this.payments = payments;
	}

	public String getExtraData() {
		return this.extraData;
	}

	public void setExtraData(String extraData) {
		this.extraData = extraData;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
