package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;

/**
 * PaymentLogs generated by hbm2java
 */
public class PaymentLogs implements java.io.Serializable {

	private int id;
	private String gatewayId;
	private Serializable data;
	private Date createdAt;
	private Date updatedAt;

	public PaymentLogs() {
	}

	public PaymentLogs(int id, String gatewayId, Serializable data) {
		this.id = id;
		this.gatewayId = gatewayId;
		this.data = data;
	}

	public PaymentLogs(int id, String gatewayId, Serializable data, Date createdAt, Date updatedAt) {
		this.id = id;
		this.gatewayId = gatewayId;
		this.data = data;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getGatewayId() {
		return this.gatewayId;
	}

	public void setGatewayId(String gatewayId) {
		this.gatewayId = gatewayId;
	}

	public Serializable getData() {
		return this.data;
	}

	public void setData(Serializable data) {
		this.data = data;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
