package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProjectAccounts generated by hbm2java
 */
public class ProjectAccounts implements java.io.Serializable {

	private int id;
	private Projects projects;
	private Banks banks;
	private String email;
	private String stateInscription;
	private String addressStreet;
	private String addressNumber;
	private String addressComplement;
	private String addressCity;
	private String addressNeighbourhood;
	private String addressState;
	private String addressZipCode;
	private String phoneNumber;
	private String agency;
	private String agencyDigit;
	private String account;
	private String accountDigit;
	private String ownerName;
	private String ownerDocument;
	private Date createdAt;
	private Date updatedAt;
	private String accountType;
	private Set<ProjectAccountErrors> projectAccountErrorses = new HashSet<ProjectAccountErrors>(0);

	public ProjectAccounts() {
	}

	public ProjectAccounts(int id, Projects projects, String email, String addressStreet, String addressNumber,
			String addressCity, String addressNeighbourhood, String addressState, String addressZipCode,
			String phoneNumber, String agency, String agencyDigit, String account, String accountDigit,
			String ownerName, String ownerDocument) {
		this.id = id;
		this.projects = projects;
		this.email = email;
		this.addressStreet = addressStreet;
		this.addressNumber = addressNumber;
		this.addressCity = addressCity;
		this.addressNeighbourhood = addressNeighbourhood;
		this.addressState = addressState;
		this.addressZipCode = addressZipCode;
		this.phoneNumber = phoneNumber;
		this.agency = agency;
		this.agencyDigit = agencyDigit;
		this.account = account;
		this.accountDigit = accountDigit;
		this.ownerName = ownerName;
		this.ownerDocument = ownerDocument;
	}

	public ProjectAccounts(int id, Projects projects, Banks banks, String email, String stateInscription,
			String addressStreet, String addressNumber, String addressComplement, String addressCity,
			String addressNeighbourhood, String addressState, String addressZipCode, String phoneNumber, String agency,
			String agencyDigit, String account, String accountDigit, String ownerName, String ownerDocument,
			Date createdAt, Date updatedAt, String accountType, Set<ProjectAccountErrors> projectAccountErrorses) {
		this.id = id;
		this.projects = projects;
		this.banks = banks;
		this.email = email;
		this.stateInscription = stateInscription;
		this.addressStreet = addressStreet;
		this.addressNumber = addressNumber;
		this.addressComplement = addressComplement;
		this.addressCity = addressCity;
		this.addressNeighbourhood = addressNeighbourhood;
		this.addressState = addressState;
		this.addressZipCode = addressZipCode;
		this.phoneNumber = phoneNumber;
		this.agency = agency;
		this.agencyDigit = agencyDigit;
		this.account = account;
		this.accountDigit = accountDigit;
		this.ownerName = ownerName;
		this.ownerDocument = ownerDocument;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.accountType = accountType;
		this.projectAccountErrorses = projectAccountErrorses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public Banks getBanks() {
		return this.banks;
	}

	public void setBanks(Banks banks) {
		this.banks = banks;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getStateInscription() {
		return this.stateInscription;
	}

	public void setStateInscription(String stateInscription) {
		this.stateInscription = stateInscription;
	}

	public String getAddressStreet() {
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	public String getAddressNumber() {
		return this.addressNumber;
	}

	public void setAddressNumber(String addressNumber) {
		this.addressNumber = addressNumber;
	}

	public String getAddressComplement() {
		return this.addressComplement;
	}

	public void setAddressComplement(String addressComplement) {
		this.addressComplement = addressComplement;
	}

	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	public String getAddressNeighbourhood() {
		return this.addressNeighbourhood;
	}

	public void setAddressNeighbourhood(String addressNeighbourhood) {
		this.addressNeighbourhood = addressNeighbourhood;
	}

	public String getAddressState() {
		return this.addressState;
	}

	public void setAddressState(String addressState) {
		this.addressState = addressState;
	}

	public String getAddressZipCode() {
		return this.addressZipCode;
	}

	public void setAddressZipCode(String addressZipCode) {
		this.addressZipCode = addressZipCode;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAgency() {
		return this.agency;
	}

	public void setAgency(String agency) {
		this.agency = agency;
	}

	public String getAgencyDigit() {
		return this.agencyDigit;
	}

	public void setAgencyDigit(String agencyDigit) {
		this.agencyDigit = agencyDigit;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAccountDigit() {
		return this.accountDigit;
	}

	public void setAccountDigit(String accountDigit) {
		this.accountDigit = accountDigit;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public String getOwnerDocument() {
		return this.ownerDocument;
	}

	public void setOwnerDocument(String ownerDocument) {
		this.ownerDocument = ownerDocument;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public Set<ProjectAccountErrors> getProjectAccountErrorses() {
		return this.projectAccountErrorses;
	}

	public void setProjectAccountErrorses(Set<ProjectAccountErrors> projectAccountErrorses) {
		this.projectAccountErrorses = projectAccountErrorses;
	}

}
