package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * ProjectReminders generated by hbm2java
 */
public class ProjectReminders implements java.io.Serializable {

	private int id;
	private Users users;
	private Projects projects;
	private Date createdAt;
	private Date updatedAt;

	public ProjectReminders() {
	}

	public ProjectReminders(int id, Users users, Projects projects) {
		this.id = id;
		this.users = users;
		this.projects = projects;
	}

	public ProjectReminders(int id, Users users, Projects projects, Date createdAt, Date updatedAt) {
		this.id = id;
		this.users = users;
		this.projects = projects;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
