package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * ProjectNotifications generated by hbm2java
 */
public class ProjectNotifications implements java.io.Serializable {

	private int id;
	private Users users;
	private Projects projects;
	private String fromEmail;
	private String fromName;
	private String templateName;
	private String locale;
	private Date sentAt;
	private Date createdAt;
	private Date updatedAt;
	private Date deliverAt;
	private String cc;

	public ProjectNotifications() {
	}

	public ProjectNotifications(int id, Users users, Projects projects, String fromEmail, String fromName,
			String templateName, String locale) {
		this.id = id;
		this.users = users;
		this.projects = projects;
		this.fromEmail = fromEmail;
		this.fromName = fromName;
		this.templateName = templateName;
		this.locale = locale;
	}

	public ProjectNotifications(int id, Users users, Projects projects, String fromEmail, String fromName,
			String templateName, String locale, Date sentAt, Date createdAt, Date updatedAt, Date deliverAt,
			String cc) {
		this.id = id;
		this.users = users;
		this.projects = projects;
		this.fromEmail = fromEmail;
		this.fromName = fromName;
		this.templateName = templateName;
		this.locale = locale;
		this.sentAt = sentAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deliverAt = deliverAt;
		this.cc = cc;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public String getFromEmail() {
		return this.fromEmail;
	}

	public void setFromEmail(String fromEmail) {
		this.fromEmail = fromEmail;
	}

	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public Date getSentAt() {
		return this.sentAt;
	}

	public void setSentAt(Date sentAt) {
		this.sentAt = sentAt;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Date getDeliverAt() {
		return this.deliverAt;
	}

	public void setDeliverAt(Date deliverAt) {
		this.deliverAt = deliverAt;
	}

	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

}
