package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

/**
 * ProjectFinancials generated by hbm2java
 */
public class ProjectFinancials implements java.io.Serializable {

	private ProjectFinancialsId id;

	public ProjectFinancials() {
	}

	public ProjectFinancials(ProjectFinancialsId id) {
		this.id = id;
	}

	public ProjectFinancialsId getId() {
		return this.id;
	}

	public void setId(ProjectFinancialsId id) {
		this.id = id;
	}

}
