package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;

/**
 * Rdevents generated by hbm2java
 */
public class Rdevents implements java.io.Serializable {

	private int id;
	private Users users;
	private Projects projects;
	private String eventName;
	private Serializable metadata;
	private Date createdAt;
	private Date updatedAt;

	public Rdevents() {
	}

	public Rdevents(int id, Users users, String eventName) {
		this.id = id;
		this.users = users;
		this.eventName = eventName;
	}

	public Rdevents(int id, Users users, Projects projects, String eventName, Serializable metadata, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.users = users;
		this.projects = projects;
		this.eventName = eventName;
		this.metadata = metadata;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public Serializable getMetadata() {
		return this.metadata;
	}

	public void setMetadata(Serializable metadata) {
		this.metadata = metadata;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
