package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * States generated by hbm2java
 */
public class States implements java.io.Serializable {

	private int id;
	private String name;
	private String acronym;
	private Date createdAt;
	private Date updatedAt;
	private Set<Cities> citieses = new HashSet<Cities>(0);

	public States() {
	}

	public States(int id, String name, String acronym) {
		this.id = id;
		this.name = name;
		this.acronym = acronym;
	}

	public States(int id, String name, String acronym, Date createdAt, Date updatedAt, Set<Cities> citieses) {
		this.id = id;
		this.name = name;
		this.acronym = acronym;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.citieses = citieses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Cities> getCitieses() {
		return this.citieses;
	}

	public void setCitieses(Set<Cities> citieses) {
		this.citieses = citieses;
	}

}
