package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

/**
 * SubscriberReports generated by hbm2java
 */
public class SubscriberReports implements java.io.Serializable {

	private SubscriberReportsId id;

	public SubscriberReports() {
	}

	public SubscriberReports(SubscriberReportsId id) {
		this.id = id;
	}

	public SubscriberReportsId getId() {
		return this.id;
	}

	public void setId(SubscriberReportsId id) {
		this.id = id;
	}

}
