package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Taggings generated by hbm2java
 */
public class Taggings implements java.io.Serializable {

	private int id;
	private Tags tags;
	private Projects projects;
	private Date createdAt;
	private Date updatedAt;

	public Taggings() {
	}

	public Taggings(int id, Tags tags, Projects projects) {
		this.id = id;
		this.tags = tags;
		this.projects = projects;
	}

	public Taggings(int id, Tags tags, Projects projects, Date createdAt, Date updatedAt) {
		this.id = id;
		this.tags = tags;
		this.projects = projects;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Tags getTags() {
		return this.tags;
	}

	public void setTags(Tags tags) {
		this.tags = tags;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
