package gensrc2;
// Generated 9 Jun, 2016 7:09:50 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private int id;
	private String name;
	private String slug;
	private Date createdAt;
	private Date updatedAt;
	private Set<Taggings> taggingses = new HashSet<Taggings>(0);

	public Tags() {
	}

	public Tags(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Tags(int id, String name, String slug, Date createdAt, Date updatedAt, Set<Taggings> taggingses) {
		this.id = id;
		this.name = name;
		this.slug = slug;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.taggingses = taggingses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Taggings> getTaggingses() {
		return this.taggingses;
	}

	public void setTaggingses(Set<Taggings> taggingses) {
		this.taggingses = taggingses;
	}

}
