package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * BalanceTransfers generated by hbm2java
 */
public class BalanceTransfers implements java.io.Serializable {

	private BalanceTransfersId id;

	public BalanceTransfers() {
	}

	public BalanceTransfers(BalanceTransfersId id) {
		this.id = id;
	}

	public BalanceTransfersId getId() {
		return this.id;
	}

	public void setId(BalanceTransfersId id) {
		this.id = id;
	}

}
