package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * BalanceTransactions generated by hbm2java
 */
public class BalanceTransactions implements java.io.Serializable {

	private BalanceTransactionsId id;

	public BalanceTransactions() {
	}

	public BalanceTransactions(BalanceTransactionsId id) {
		this.id = id;
	}

	public BalanceTransactionsId getId() {
		return this.id;
	}

	public void setId(BalanceTransactionsId id) {
		this.id = id;
	}

}
