package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * BankAccounts generated by hbm2java
 */
public class BankAccounts implements java.io.Serializable {

	private BankAccountsId id;

	public BankAccounts() {
	}

	public BankAccounts(BankAccountsId id) {
		this.id = id;
	}

	public BankAccountsId getId() {
		return this.id;
	}

	public void setId(BankAccountsId id) {
		this.id = id;
	}

}
