package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * CategoryFollowers generated by hbm2java
 */
public class CategoryFollowers implements java.io.Serializable {

	private CategoryFollowersId id;

	public CategoryFollowers() {
	}

	public CategoryFollowers(CategoryFollowersId id) {
		this.id = id;
	}

	public CategoryFollowersId getId() {
		return this.id;
	}

	public void setId(CategoryFollowersId id) {
		this.id = id;
	}

}
