package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * CategoryFollowersId generated by hbm2java
 */
public class CategoryFollowersId implements java.io.Serializable {

	private Integer categoryId;
	private Integer userId;

	public CategoryFollowersId() {
	}

	public CategoryFollowersId(Integer categoryId, Integer userId) {
		this.categoryId = categoryId;
		this.userId = userId;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryFollowersId))
			return false;
		CategoryFollowersId castOther = (CategoryFollowersId) other;

		return ((this.getCategoryId() == castOther.getCategoryId()) || (this.getCategoryId() != null
				&& castOther.getCategoryId() != null && this.getCategoryId().equals(castOther.getCategoryId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCategoryId() == null ? 0 : this.getCategoryId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
