package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ContributionActivities generated by hbm2java
 */
public class ContributionActivities implements java.io.Serializable {

	private ContributionActivitiesId id;

	public ContributionActivities() {
	}

	public ContributionActivities(ContributionActivitiesId id) {
		this.id = id;
	}

	public ContributionActivitiesId getId() {
		return this.id;
	}

	public void setId(ContributionActivitiesId id) {
		this.id = id;
	}

}
