package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ContributionReportsForProjectOwners generated by hbm2java
 */
public class ContributionReportsForProjectOwners implements java.io.Serializable {

	private ContributionReportsForProjectOwnersId id;

	public ContributionReportsForProjectOwners() {
	}

	public ContributionReportsForProjectOwners(ContributionReportsForProjectOwnersId id) {
		this.id = id;
	}

	public ContributionReportsForProjectOwnersId getId() {
		return this.id;
	}

	public void setId(ContributionReportsForProjectOwnersId id) {
		this.id = id;
	}

}
