package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * DirectMessages generated by hbm2java
 */
public class DirectMessages implements java.io.Serializable {

	private DirectMessagesId id;

	public DirectMessages() {
	}

	public DirectMessages(DirectMessagesId id) {
		this.id = id;
	}

	public DirectMessagesId getId() {
		return this.id;
	}

	public void setId(DirectMessagesId id) {
		this.id = id;
	}

}
