package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * Notifications generated by hbm2java
 */
public class Notifications implements java.io.Serializable {

	private NotificationsId id;

	public Notifications() {
	}

	public Notifications(NotificationsId id) {
		this.id = id;
	}

	public NotificationsId getId() {
		return this.id;
	}

	public void setId(NotificationsId id) {
		this.id = id;
	}

}
