package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ProjectContributionsPerRef generated by hbm2java
 */
public class ProjectContributionsPerRef implements java.io.Serializable {

	private ProjectContributionsPerRefId id;

	public ProjectContributionsPerRef() {
	}

	public ProjectContributionsPerRef(ProjectContributionsPerRefId id) {
		this.id = id;
	}

	public ProjectContributionsPerRefId getId() {
		return this.id;
	}

	public void setId(ProjectContributionsPerRefId id) {
		this.id = id;
	}

}
