package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ProjectTransitions generated by hbm2java
 */
public class ProjectTransitions implements java.io.Serializable {

	private ProjectTransitionsId id;

	public ProjectTransitions() {
	}

	public ProjectTransitions(ProjectTransitionsId id) {
		this.id = id;
	}

	public ProjectTransitionsId getId() {
		return this.id;
	}

	public void setId(ProjectTransitionsId id) {
		this.id = id;
	}

}
