package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ProjectReports generated by hbm2java
 */
public class ProjectReports implements java.io.Serializable {

	private ProjectReportsId id;

	public ProjectReports() {
	}

	public ProjectReports(ProjectReportsId id) {
		this.id = id;
	}

	public ProjectReportsId getId() {
		return this.id;
	}

	public void setId(ProjectReportsId id) {
		this.id = id;
	}

}
