package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ProjectScores generated by hbm2java
 */
public class ProjectScores implements java.io.Serializable {

	private ProjectScoresId id;

	public ProjectScores() {
	}

	public ProjectScores(ProjectScoresId id) {
		this.id = id;
	}

	public ProjectScoresId getId() {
		return this.id;
	}

	public void setId(ProjectScoresId id) {
		this.id = id;
	}

}
