package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * ProjectTotalsId generated by hbm2java
 */
public class ProjectTotalsId implements java.io.Serializable {

	private Integer projectId;
	private BigDecimal pledged;
	private BigDecimal paidPledged;
	private BigDecimal progress;
	private BigDecimal totalPaymentServiceFee;
	private BigDecimal paidTotalPaymentServiceFee;
	private Long totalContributions;
	private Long totalContributors;

	public ProjectTotalsId() {
	}

	public ProjectTotalsId(Integer projectId, BigDecimal pledged, BigDecimal paidPledged, BigDecimal progress,
			BigDecimal totalPaymentServiceFee, BigDecimal paidTotalPaymentServiceFee, Long totalContributions,
			Long totalContributors) {
		this.projectId = projectId;
		this.pledged = pledged;
		this.paidPledged = paidPledged;
		this.progress = progress;
		this.totalPaymentServiceFee = totalPaymentServiceFee;
		this.paidTotalPaymentServiceFee = paidTotalPaymentServiceFee;
		this.totalContributions = totalContributions;
		this.totalContributors = totalContributors;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public BigDecimal getPledged() {
		return this.pledged;
	}

	public void setPledged(BigDecimal pledged) {
		this.pledged = pledged;
	}

	public BigDecimal getPaidPledged() {
		return this.paidPledged;
	}

	public void setPaidPledged(BigDecimal paidPledged) {
		this.paidPledged = paidPledged;
	}

	public BigDecimal getProgress() {
		return this.progress;
	}

	public void setProgress(BigDecimal progress) {
		this.progress = progress;
	}

	public BigDecimal getTotalPaymentServiceFee() {
		return this.totalPaymentServiceFee;
	}

	public void setTotalPaymentServiceFee(BigDecimal totalPaymentServiceFee) {
		this.totalPaymentServiceFee = totalPaymentServiceFee;
	}

	public BigDecimal getPaidTotalPaymentServiceFee() {
		return this.paidTotalPaymentServiceFee;
	}

	public void setPaidTotalPaymentServiceFee(BigDecimal paidTotalPaymentServiceFee) {
		this.paidTotalPaymentServiceFee = paidTotalPaymentServiceFee;
	}

	public Long getTotalContributions() {
		return this.totalContributions;
	}

	public void setTotalContributions(Long totalContributions) {
		this.totalContributions = totalContributions;
	}

	public Long getTotalContributors() {
		return this.totalContributors;
	}

	public void setTotalContributors(Long totalContributors) {
		this.totalContributors = totalContributors;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectTotalsId))
			return false;
		ProjectTotalsId castOther = (ProjectTotalsId) other;

		return ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
				&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getPledged() == castOther.getPledged()) || (this.getPledged() != null
						&& castOther.getPledged() != null && this.getPledged().equals(castOther.getPledged())))
				&& ((this.getPaidPledged() == castOther.getPaidPledged())
						|| (this.getPaidPledged() != null && castOther.getPaidPledged() != null
								&& this.getPaidPledged().equals(castOther.getPaidPledged())))
				&& ((this.getProgress() == castOther.getProgress()) || (this.getProgress() != null
						&& castOther.getProgress() != null && this.getProgress().equals(castOther.getProgress())))
				&& ((this.getTotalPaymentServiceFee() == castOther.getTotalPaymentServiceFee())
						|| (this.getTotalPaymentServiceFee() != null && castOther.getTotalPaymentServiceFee() != null
								&& this.getTotalPaymentServiceFee().equals(castOther.getTotalPaymentServiceFee())))
				&& ((this.getPaidTotalPaymentServiceFee() == castOther.getPaidTotalPaymentServiceFee())
						|| (this.getPaidTotalPaymentServiceFee() != null
								&& castOther.getPaidTotalPaymentServiceFee() != null
								&& this.getPaidTotalPaymentServiceFee()
										.equals(castOther.getPaidTotalPaymentServiceFee())))
				&& ((this.getTotalContributions() == castOther.getTotalContributions())
						|| (this.getTotalContributions() != null && castOther.getTotalContributions() != null
								&& this.getTotalContributions().equals(castOther.getTotalContributions())))
				&& ((this.getTotalContributors() == castOther.getTotalContributors())
						|| (this.getTotalContributors() != null && castOther.getTotalContributors() != null
								&& this.getTotalContributors().equals(castOther.getTotalContributors())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getPledged() == null ? 0 : this.getPledged().hashCode());
		result = 37 * result + (getPaidPledged() == null ? 0 : this.getPaidPledged().hashCode());
		result = 37 * result + (getProgress() == null ? 0 : this.getProgress().hashCode());
		result = 37 * result + (getTotalPaymentServiceFee() == null ? 0 : this.getTotalPaymentServiceFee().hashCode());
		result = 37 * result
				+ (getPaidTotalPaymentServiceFee() == null ? 0 : this.getPaidTotalPaymentServiceFee().hashCode());
		result = 37 * result + (getTotalContributions() == null ? 0 : this.getTotalContributions().hashCode());
		result = 37 * result + (getTotalContributors() == null ? 0 : this.getTotalContributors().hashCode());
		return result;
	}

}
