package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ProjectAccountErrors generated by hbm2java
 */
public class ProjectAccountErrors implements java.io.Serializable {

	private ProjectAccountErrorsId id;

	public ProjectAccountErrors() {
	}

	public ProjectAccountErrors(ProjectAccountErrorsId id) {
		this.id = id;
	}

	public ProjectAccountErrorsId getId() {
		return this.id;
	}

	public void setId(ProjectAccountErrorsId id) {
		this.id = id;
	}

}
