package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ProjectAccounts generated by hbm2java
 */
public class ProjectAccounts implements java.io.Serializable {

	private ProjectAccountsId id;

	public ProjectAccounts() {
	}

	public ProjectAccounts(ProjectAccountsId id) {
		this.id = id;
	}

	public ProjectAccountsId getId() {
		return this.id;
	}

	public void setId(ProjectAccountsId id) {
		this.id = id;
	}

}
