package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * ReferralTotals generated by hbm2java
 */
public class ReferralTotals implements java.io.Serializable {

	private ReferralTotalsId id;

	public ReferralTotals() {
	}

	public ReferralTotals(ReferralTotalsId id) {
		this.id = id;
	}

	public ReferralTotalsId getId() {
		return this.id;
	}

	public void setId(ReferralTotalsId id) {
		this.id = id;
	}

}
