package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * TeamTotals generated by hbm2java
 */
public class TeamTotals implements java.io.Serializable {

	private TeamTotalsId id;

	public TeamTotals() {
	}

	public TeamTotals(TeamTotalsId id) {
		this.id = id;
	}

	public TeamTotalsId getId() {
		return this.id;
	}

	public void setId(TeamTotalsId id) {
		this.id = id;
	}

}
