package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * TeamMembers generated by hbm2java
 */
public class TeamMembers implements java.io.Serializable {

	private TeamMembersId id;

	public TeamMembers() {
	}

	public TeamMembers(TeamMembersId id) {
		this.id = id;
	}

	public TeamMembersId getId() {
		return this.id;
	}

	public void setId(TeamMembersId id) {
		this.id = id;
	}

}
