package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * UserFriendsId generated by hbm2java
 */
public class UserFriendsId implements java.io.Serializable {

	private Integer userId;
	private Integer friendId;
	private Boolean following;
	private String name;
	private String avatar;
	private Long totalContributedProjects;
	private Long totalPublishedProjects;
	private String city;
	private String state;

	public UserFriendsId() {
	}

	public UserFriendsId(Integer userId, Integer friendId, Boolean following, String name, String avatar,
			Long totalContributedProjects, Long totalPublishedProjects, String city, String state) {
		this.userId = userId;
		this.friendId = friendId;
		this.following = following;
		this.name = name;
		this.avatar = avatar;
		this.totalContributedProjects = totalContributedProjects;
		this.totalPublishedProjects = totalPublishedProjects;
		this.city = city;
		this.state = state;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	public Boolean getFollowing() {
		return this.following;
	}

	public void setFollowing(Boolean following) {
		this.following = following;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Long getTotalContributedProjects() {
		return this.totalContributedProjects;
	}

	public void setTotalContributedProjects(Long totalContributedProjects) {
		this.totalContributedProjects = totalContributedProjects;
	}

	public Long getTotalPublishedProjects() {
		return this.totalPublishedProjects;
	}

	public void setTotalPublishedProjects(Long totalPublishedProjects) {
		this.totalPublishedProjects = totalPublishedProjects;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserFriendsId))
			return false;
		UserFriendsId castOther = (UserFriendsId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getFriendId() == castOther.getFriendId()) || (this.getFriendId() != null
						&& castOther.getFriendId() != null && this.getFriendId().equals(castOther.getFriendId())))
				&& ((this.getFollowing() == castOther.getFollowing()) || (this.getFollowing() != null
						&& castOther.getFollowing() != null && this.getFollowing().equals(castOther.getFollowing())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getAvatar() == castOther.getAvatar()) || (this.getAvatar() != null
						&& castOther.getAvatar() != null && this.getAvatar().equals(castOther.getAvatar())))
				&& ((this.getTotalContributedProjects() == castOther.getTotalContributedProjects())
						|| (this.getTotalContributedProjects() != null
								&& castOther.getTotalContributedProjects() != null
								&& this.getTotalContributedProjects().equals(castOther.getTotalContributedProjects())))
				&& ((this.getTotalPublishedProjects() == castOther.getTotalPublishedProjects())
						|| (this.getTotalPublishedProjects() != null && castOther.getTotalPublishedProjects() != null
								&& this.getTotalPublishedProjects().equals(castOther.getTotalPublishedProjects())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getFriendId() == null ? 0 : this.getFriendId().hashCode());
		result = 37 * result + (getFollowing() == null ? 0 : this.getFollowing().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getAvatar() == null ? 0 : this.getAvatar().hashCode());
		result = 37 * result
				+ (getTotalContributedProjects() == null ? 0 : this.getTotalContributedProjects().hashCode());
		result = 37 * result + (getTotalPublishedProjects() == null ? 0 : this.getTotalPublishedProjects().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		return result;
	}

}
