package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * UserCredits generated by hbm2java
 */
public class UserCredits implements java.io.Serializable {

	private UserCreditsId id;

	public UserCredits() {
	}

	public UserCredits(UserCreditsId id) {
		this.id = id;
	}

	public UserCreditsId getId() {
		return this.id;
	}

	public void setId(UserCreditsId id) {
		this.id = id;
	}

}
