package gensrc1;
// Generated 9 Jun, 2016 7:06:41 PM by Hibernate Tools 4.0.0.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private UsersId id;

	public Users() {
	}

	public Users(UsersId id) {
		this.id = id;
	}

	public UsersId getId() {
		return this.id;
	}

	public void setId(UsersId id) {
		this.id = id;
	}

}
