package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditCards generated by hbm2java
 */
@Entity
@Table(name = "credit_cards", schema = "public")
public class CreditCards implements java.io.Serializable {

	private int id;
	private Users users;
	private String lastDigits;
	private String cardBrand;
	private String subscriptionId;
	private Date createdAt;
	private Date updatedAt;
	private String cardKey;

	public CreditCards() {
	}

	public CreditCards(int id, String lastDigits, String cardBrand) {
		this.id = id;
		this.lastDigits = lastDigits;
		this.cardBrand = cardBrand;
	}

	public CreditCards(int id, Users users, String lastDigits, String cardBrand, String subscriptionId, Date createdAt,
			Date updatedAt, String cardKey) {
		this.id = id;
		this.users = users;
		this.lastDigits = lastDigits;
		this.cardBrand = cardBrand;
		this.subscriptionId = subscriptionId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.cardKey = cardKey;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "last_digits", nullable = false)
	public String getLastDigits() {
		return this.lastDigits;
	}

	public void setLastDigits(String lastDigits) {
		this.lastDigits = lastDigits;
	}

	@Column(name = "card_brand", nullable = false)
	public String getCardBrand() {
		return this.cardBrand;
	}

	public void setCardBrand(String cardBrand) {
		this.cardBrand = cardBrand;
	}

	@Column(name = "subscription_id")
	public String getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(String subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "card_key")
	public String getCardKey() {
		return this.cardKey;
	}

	public void setCardKey(String cardKey) {
		this.cardKey = cardKey;
	}

}
