package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FlexibleProjectStates generated by hbm2java
 */
@Entity
@Table(name = "flexible_project_states", schema = "public")
public class FlexibleProjectStates implements java.io.Serializable {

	private String state;
	private Serializable stateOrder;
	private Set<FlexibleProjects> flexibleProjectses = new HashSet<FlexibleProjects>(0);
	private Set<FlexibleProjectTransitions> flexibleProjectTransitionses = new HashSet<FlexibleProjectTransitions>(0);

	public FlexibleProjectStates() {
	}

	public FlexibleProjectStates(String state, Serializable stateOrder) {
		this.state = state;
		this.stateOrder = stateOrder;
	}

	public FlexibleProjectStates(String state, Serializable stateOrder, Set<FlexibleProjects> flexibleProjectses,
			Set<FlexibleProjectTransitions> flexibleProjectTransitionses) {
		this.state = state;
		this.stateOrder = stateOrder;
		this.flexibleProjectses = flexibleProjectses;
		this.flexibleProjectTransitionses = flexibleProjectTransitionses;
	}

	@Id

	@Column(name = "state", unique = true, nullable = false)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "state_order", nullable = false)
	public Serializable getStateOrder() {
		return this.stateOrder;
	}

	public void setStateOrder(Serializable stateOrder) {
		this.stateOrder = stateOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flexibleProjectStates")
	public Set<FlexibleProjects> getFlexibleProjectses() {
		return this.flexibleProjectses;
	}

	public void setFlexibleProjectses(Set<FlexibleProjects> flexibleProjectses) {
		this.flexibleProjectses = flexibleProjectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flexibleProjectStates")
	public Set<FlexibleProjectTransitions> getFlexibleProjectTransitionses() {
		return this.flexibleProjectTransitionses;
	}

	public void setFlexibleProjectTransitionses(Set<FlexibleProjectTransitions> flexibleProjectTransitionses) {
		this.flexibleProjectTransitionses = flexibleProjectTransitionses;
	}

}
