package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NearMes generated by hbm2java
 */
@Entity
@Table(name = "near_mes", schema = "public")
public class NearMes implements java.io.Serializable {

	private int id;

	public NearMes() {
	}

	public NearMes(int id) {
		this.id = id;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
