package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Origins generated by hbm2java
 */
@Entity
@Table(name = "origins", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "domain",
		"referral" }) )
public class Origins implements java.io.Serializable {

	private int id;
	private String domain;
	private String referral;
	private Date createdAt;
	private Date updatedAt;
	private Set<Contributions> contributionses = new HashSet<Contributions>(0);
	private Set<Projects> projectses = new HashSet<Projects>(0);

	public Origins() {
	}

	public Origins(int id, String domain) {
		this.id = id;
		this.domain = domain;
	}

	public Origins(int id, String domain, String referral, Date createdAt, Date updatedAt,
			Set<Contributions> contributionses, Set<Projects> projectses) {
		this.id = id;
		this.domain = domain;
		this.referral = referral;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.contributionses = contributionses;
		this.projectses = projectses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "domain", nullable = false)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "referral")
	public String getReferral() {
		return this.referral;
	}

	public void setReferral(String referral) {
		this.referral = referral;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "origins")
	public Set<Contributions> getContributionses() {
		return this.contributionses;
	}

	public void setContributionses(Set<Contributions> contributionses) {
		this.contributionses = contributionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "origins")
	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

}
