package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PaymentLogs generated by hbm2java
 */
@Entity
@Table(name = "payment_logs", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "gateway_id") )
public class PaymentLogs implements java.io.Serializable {

	private int id;
	private String gatewayId;
	private Serializable data;
	private Date createdAt;
	private Date updatedAt;

	public PaymentLogs() {
	}

	public PaymentLogs(int id, String gatewayId, Serializable data) {
		this.id = id;
		this.gatewayId = gatewayId;
		this.data = data;
	}

	public PaymentLogs(int id, String gatewayId, Serializable data, Date createdAt, Date updatedAt) {
		this.id = id;
		this.gatewayId = gatewayId;
		this.data = data;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "gateway_id", unique = true, nullable = false)
	public String getGatewayId() {
		return this.gatewayId;
	}

	public void setGatewayId(String gatewayId) {
		this.gatewayId = gatewayId;
	}

	@Column(name = "data", nullable = false)
	public Serializable getData() {
		return this.data;
	}

	public void setData(Serializable data) {
		this.data = data;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
