package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectAccountErrors generated by hbm2java
 */
@Entity
@Table(name = "project_account_errors", schema = "public")
public class ProjectAccountErrors implements java.io.Serializable {

	private int id;
	private ProjectAccounts projectAccounts;
	private String reason;
	private Boolean solved;
	private Date solvedAt;
	private Date createdAt;
	private Date updatedAt;

	public ProjectAccountErrors() {
	}

	public ProjectAccountErrors(int id, ProjectAccounts projectAccounts, String reason) {
		this.id = id;
		this.projectAccounts = projectAccounts;
		this.reason = reason;
	}

	public ProjectAccountErrors(int id, ProjectAccounts projectAccounts, String reason, Boolean solved, Date solvedAt,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.projectAccounts = projectAccounts;
		this.reason = reason;
		this.solved = solved;
		this.solvedAt = solvedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_account_id", nullable = false)
	public ProjectAccounts getProjectAccounts() {
		return this.projectAccounts;
	}

	public void setProjectAccounts(ProjectAccounts projectAccounts) {
		this.projectAccounts = projectAccounts;
	}

	@Column(name = "reason", nullable = false)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "solved")
	public Boolean getSolved() {
		return this.solved;
	}

	public void setSolved(Boolean solved) {
		this.solved = solved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "solved_at", length = 29)
	public Date getSolvedAt() {
		return this.solvedAt;
	}

	public void setSolvedAt(Date solvedAt) {
		this.solvedAt = solvedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
