package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectFinancials generated by hbm2java
 */
@Entity
@Table(name = "project_financials", schema = "public")
public class ProjectFinancials implements java.io.Serializable {

	private ProjectFinancialsId id;

	public ProjectFinancials() {
	}

	public ProjectFinancials(ProjectFinancialsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "projectId", column = @Column(name = "project_id") ),
			@AttributeOverride(name = "name", column = @Column(name = "name") ),
			@AttributeOverride(name = "moip", column = @Column(name = "moip") ),
			@AttributeOverride(name = "goal", column = @Column(name = "goal", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "reached", column = @Column(name = "reached", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "paymentTax", column = @Column(name = "payment_tax", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "catarseFee", column = @Column(name = "catarse_fee", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "repassValue", column = @Column(name = "repass_value", precision = 131089, scale = 0) ),
			@AttributeOverride(name = "expiresAt", column = @Column(name = "expires_at") ),
			@AttributeOverride(name = "contributionReport", column = @Column(name = "contribution_report") ),
			@AttributeOverride(name = "state", column = @Column(name = "state") ) })
	public ProjectFinancialsId getId() {
		return this.id;
	}

	public void setId(ProjectFinancialsId id) {
		this.id = id;
	}

}
