package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SendgridEvents generated by hbm2java
 */
@Entity
@Table(name = "sendgrid_events", schema = "public")
public class SendgridEvents implements java.io.Serializable {

	private int id;
	private int notificationId;
	private int notificationUser;
	private String notificationType;
	private String templateName;
	private String event;
	private String email;
	private String useragent;
	private Serializable sendgridData;
	private Date createdAt;
	private Date updatedAt;

	public SendgridEvents() {
	}

	public SendgridEvents(int id, int notificationId, int notificationUser, String notificationType,
			String templateName, String event, String email, Serializable sendgridData) {
		this.id = id;
		this.notificationId = notificationId;
		this.notificationUser = notificationUser;
		this.notificationType = notificationType;
		this.templateName = templateName;
		this.event = event;
		this.email = email;
		this.sendgridData = sendgridData;
	}

	public SendgridEvents(int id, int notificationId, int notificationUser, String notificationType,
			String templateName, String event, String email, String useragent, Serializable sendgridData,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.notificationId = notificationId;
		this.notificationUser = notificationUser;
		this.notificationType = notificationType;
		this.templateName = templateName;
		this.event = event;
		this.email = email;
		this.useragent = useragent;
		this.sendgridData = sendgridData;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "notification_id", nullable = false)
	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "notification_user", nullable = false)
	public int getNotificationUser() {
		return this.notificationUser;
	}

	public void setNotificationUser(int notificationUser) {
		this.notificationUser = notificationUser;
	}

	@Column(name = "notification_type", nullable = false)
	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	@Column(name = "template_name", nullable = false)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "event", nullable = false)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "useragent")
	public String getUseragent() {
		return this.useragent;
	}

	public void setUseragent(String useragent) {
		this.useragent = useragent;
	}

	@Column(name = "sendgrid_data", nullable = false)
	public Serializable getSendgridData() {
		return this.sendgridData;
	}

	public void setSendgridData(Serializable sendgridData) {
		this.sendgridData = sendgridData;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
