package ew;
// Generated 10 Jun, 2016 12:07:08 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserFriends generated by hbm2java
 */
@Entity
@Table(name = "user_friends", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "user_id",
		"friend_id" }) )
public class UserFriends implements java.io.Serializable {

	private int id;
	private Users usersByUserId;
	private Users usersByFriendId;
	private Date createdAt;
	private Date updatedAt;

	public UserFriends() {
	}

	public UserFriends(int id) {
		this.id = id;
	}

	public UserFriends(int id, Users usersByUserId, Users usersByFriendId, Date createdAt, Date updatedAt) {
		this.id = id;
		this.usersByUserId = usersByUserId;
		this.usersByFriendId = usersByFriendId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "friend_id")
	public Users getUsersByFriendId() {
		return this.usersByFriendId;
	}

	public void setUsersByFriendId(Users usersByFriendId) {
		this.usersByFriendId = usersByFriendId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 29)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
